// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: proto/simple_grpc_server/bootstrap.proto

package conf

import (
	v1 "github.com/origadmin/runtime/api/gen/go/transport/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap 是一个只提供 gRPC 服务端的微服务的顶层配置示例
type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 定义一个服务端，这里使用 repeated 是为了未来可以扩展为多个服务端
	// 例如，一个 gRPC 对内，一个 HTTP 对外
	Servers       []*v1.Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_proto_simple_grpc_server_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_grpc_server_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_proto_simple_grpc_server_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServers() []*v1.Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

var File_proto_simple_grpc_server_bootstrap_proto protoreflect.FileDescriptor

const file_proto_simple_grpc_server_bootstrap_proto_rawDesc = "" +
	"\n" +
	"(proto/simple_grpc_server/bootstrap.proto\x12\x1bexamples.simple_grpc_server\x1a\x19transport/v1/server.proto\";\n" +
	"\tBootstrap\x12.\n" +
	"\aservers\x18\x01 \x03(\v2\x14.transport.v1.ServerR\aserversB Z\x1e./simple_grpc_server/conf;confb\x06proto3"

var (
	file_proto_simple_grpc_server_bootstrap_proto_rawDescOnce sync.Once
	file_proto_simple_grpc_server_bootstrap_proto_rawDescData []byte
)

func file_proto_simple_grpc_server_bootstrap_proto_rawDescGZIP() []byte {
	file_proto_simple_grpc_server_bootstrap_proto_rawDescOnce.Do(func() {
		file_proto_simple_grpc_server_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simple_grpc_server_bootstrap_proto_rawDesc), len(file_proto_simple_grpc_server_bootstrap_proto_rawDesc)))
	})
	return file_proto_simple_grpc_server_bootstrap_proto_rawDescData
}

var file_proto_simple_grpc_server_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_simple_grpc_server_bootstrap_proto_goTypes = []any{
	(*Bootstrap)(nil), // 0: examples.simple_grpc_server.Bootstrap
	(*v1.Server)(nil), // 1: transport.v1.Server
}
var file_proto_simple_grpc_server_bootstrap_proto_depIdxs = []int32{
	1, // 0: examples.simple_grpc_server.Bootstrap.servers:type_name -> transport.v1.Server
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_simple_grpc_server_bootstrap_proto_init() }
func file_proto_simple_grpc_server_bootstrap_proto_init() {
	if File_proto_simple_grpc_server_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simple_grpc_server_bootstrap_proto_rawDesc), len(file_proto_simple_grpc_server_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_simple_grpc_server_bootstrap_proto_goTypes,
		DependencyIndexes: file_proto_simple_grpc_server_bootstrap_proto_depIdxs,
		MessageInfos:      file_proto_simple_grpc_server_bootstrap_proto_msgTypes,
	}.Build()
	File_proto_simple_grpc_server_bootstrap_proto = out.File
	file_proto_simple_grpc_server_bootstrap_proto_goTypes = nil
	file_proto_simple_grpc_server_bootstrap_proto_depIdxs = nil
}
