// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from kratos.go.

// Package registry contains generated code by adptool.
package registry

import (
	registry "github.com/go-kratos/kratos/v2/registry"
)

type (
	KratosDiscovery       = registry.Discovery
	KratosRegistrar       = registry.Registrar
	KratosServiceInstance = registry.ServiceInstance
	KratosWatcher         = registry.Watcher
)
