run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/origadmin/framework

linters:
  enable:
    - goimports
    - revive
    - govet
    - staticcheck
    - unused
    - unparam
    - nakedret
    - prealloc
    - misspell
    - errcheck
    - stylecheck
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gosec
    - lll
    - funlen
    - wsl
    - whitespace
    - dogsled
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - interfacer
    - makezero
    - scopelint
    - tagliatelle
    - testpackage
    - tparallel
    - wrapcheck
    - exportloopref
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - perfsprint
    - typecheck
    - asciicheck
    - contextcheck
    - decorder
    - depguard
    - exhaustivestruct
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - godot
    - gofumpt
    - gomnd
    - gomoddirectives
    - gosec
    - ifshort
    - importas
    - interfacebloat
    - loggercheck
    - maintidx
    - nestif
    - nilnil
    - nlreturn
    - nonamedreturns
    - promlinter
    - protogetter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

