// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from kratos.go.

// Package log contains generated code by adptool.
package log

import (
	"context"
	"io"

	klog "github.com/go-kratos/kratos/v2/log"
)

const (
	LevelDebug = klog.LevelDebug
	LevelError = klog.LevelError
	LevelFatal = klog.LevelFatal
	LevelInfo  = klog.LevelInfo
	LevelKey   = klog.LevelKey
	LevelWarn  = klog.LevelWarn
)

var (
	DefaultCaller     = klog.DefaultCaller
	DefaultLogger     = klog.DefaultLogger
	DefaultMessageKey = klog.DefaultMessageKey
	DefaultTimestamp  = klog.DefaultTimestamp
)

type (
	KratosFilter         = klog.Filter
	KratosFilterOption   = klog.FilterOption
	KratosHelper         = klog.Helper
	KratosLevel          = klog.Level
	KratosLogger         = klog.Logger
	KratosOption         = klog.Option
	KratosValuer         = klog.Valuer
	KratosWriterOptionFn = klog.WriterOptionFn
)

func KratosCaller(depth int) klog.Valuer {
	return klog.Caller(depth)
}

func KratosContext(ctx context.Context) *klog.Helper {
	return klog.Context(ctx)
}

func KratosDebug(a ...any) {
	klog.Debug(a...)
}

func KratosDebugf(format string, a ...any) {
	klog.Debugf(format, a...)
}

func KratosDebugw(keyvals ...any) {
	klog.Debugw(keyvals...)
}

func KratosError(a ...any) {
	klog.Error(a...)
}

func KratosErrorf(format string, a ...any) {
	klog.Errorf(format, a...)
}

func KratosErrorw(keyvals ...any) {
	klog.Errorw(keyvals...)
}

func KratosFatal(a ...any) {
	klog.Fatal(a...)
}

func KratosFatalf(format string, a ...any) {
	klog.Fatalf(format, a...)
}

func KratosFatalw(keyvals ...any) {
	klog.Fatalw(keyvals...)
}

func KratosFilterKey(key ...string) klog.FilterOption {
	return klog.FilterKey(key...)
}

func KratosFilterLevel(level klog.Level) klog.FilterOption {
	return klog.FilterLevel(level)
}

func KratosFilterValue(value ...string) klog.FilterOption {
	return klog.FilterValue(value...)
}

func KratosGetLogger() klog.Logger {
	return klog.GetLogger()
}

func KratosInfo(a ...any) {
	klog.Info(a...)
}

func KratosInfof(format string, a ...any) {
	klog.Infof(format, a...)
}

func KratosInfow(keyvals ...any) {
	klog.Infow(keyvals...)
}

func KratosLog(level klog.Level, keyvals ...any) {
	klog.Log(level, keyvals...)
}

func KratosNewFilter(logger klog.Logger, opts ...klog.FilterOption) *klog.Filter {
	return klog.NewFilter(logger, opts...)
}

func KratosNewHelper(logger klog.Logger, opts ...klog.Option) *klog.Helper {
	return klog.NewHelper(logger, opts...)
}

func KratosNewStdLogger(w io.Writer) klog.Logger {
	return klog.NewStdLogger(w)
}

func KratosNewWriter(logger klog.Logger, opts ...klog.WriterOptionFn) io.Writer {
	return klog.NewWriter(logger, opts...)
}

func KratosParseLevel(s string) klog.Level {
	return klog.ParseLevel(s)
}

func KratosSetLogger(logger klog.Logger) {
	klog.SetLogger(logger)
}

func KratosTimestamp(layout string) klog.Valuer {
	return klog.Timestamp(layout)
}

func KratosValue(ctx context.Context, v any) any {
	return klog.Value(ctx, v)
}

func KratosWarn(a ...any) {
	klog.Warn(a...)
}

func KratosWarnf(format string, a ...any) {
	klog.Warnf(format, a...)
}

func KratosWarnw(keyvals ...any) {
	klog.Warnw(keyvals...)
}

func KratosWith(l klog.Logger, kv ...any) klog.Logger {
	return klog.With(l, kv...)
}

func KratosWithContext(ctx context.Context, l klog.Logger) klog.Logger {
	return klog.WithContext(ctx, l)
}

func KratosWithMessageKey(k string) klog.Option {
	return klog.WithMessageKey(k)
}

func KratosWithSprint(sprint func(...any) string) klog.Option {
	return klog.WithSprint(sprint)
}

func KratosWithWriteMessageKey(key string) klog.WriterOptionFn {
	return klog.WithWriteMessageKey(key)
}

func KratosWithWriterLevel(level klog.Level) klog.WriterOptionFn {
	return klog.WithWriterLevel(level)
}
