# API Gateway Configuration
servers:
  # HTTP server for external access
  - http:
      network: tcp
      addr: ":8080"
      timeout: 1s
  # gRPC server for internal access
  - grpc:
      network: tcp
      addr: ":9090"
      timeout: 1s

clients:
  # Configuration for the downstream 'user-service'
  user-service:
    client: {} # Simplified to an empty client object
