// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: test/integration/app/proto/bootstrap.proto

package configs

import (
	v1 "github.com/origadmin/runtime/api/gen/go/config/discovery/v1"
	v12 "github.com/origadmin/runtime/api/gen/go/config/middleware/v1"
	v11 "github.com/origadmin/runtime/api/gen/go/config/transport/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//  1. Construct the top-level Bootstrap "blueprint"
//     This is the final application, composed entirely of the assembled components above.
type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Discovery configuration pool.
	Discoveries map[string]*v1.Discovery `protobuf:"bytes,1,rep,name=discoveries,proto3" json:"discoveries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Name of the discovery configuration used for service registration.
	RegistrationDiscoveryName string `protobuf:"bytes,2,opt,name=registration_discovery_name,json=registrationDiscoveryName,proto3" json:"registration_discovery_name,omitempty"`
	// Use our assembled `Server` components to construct a unified server list.
	Servers []*v11.Server `protobuf:"bytes,3,rep,name=servers,proto3" json:"servers,omitempty"`
	// Use our assembled `Client` components to construct a client list, where each client has its exclusive configuration.
	Clients *v11.Clients `protobuf:"bytes,4,opt,name=clients,proto3,oneof" json:"clients,omitempty"`
	// Middlewares defines the global middleware chain.
	Middlewares   *v12.Middlewares `protobuf:"bytes,5,opt,name=middlewares,proto3" json:"middlewares,omitempty"` // Added middlewares field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_test_integration_app_proto_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_test_integration_app_proto_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_test_integration_app_proto_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetDiscoveries() map[string]*v1.Discovery {
	if x != nil {
		return x.Discoveries
	}
	return nil
}

func (x *Bootstrap) GetRegistrationDiscoveryName() string {
	if x != nil {
		return x.RegistrationDiscoveryName
	}
	return ""
}

func (x *Bootstrap) GetServers() []*v11.Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Bootstrap) GetClients() *v11.Clients {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *Bootstrap) GetMiddlewares() *v12.Middlewares {
	if x != nil {
		return x.Middlewares
	}
	return nil
}

var File_test_integration_app_proto_bootstrap_proto protoreflect.FileDescriptor

const file_test_integration_app_proto_bootstrap_proto_rawDesc = "" +
	"\n" +
	"*test/integration/app/proto/bootstrap.proto\x12\x18runtime.test.app.configs\x1a#config/discovery/v1/discovery.proto\x1a%config/middleware/v1/middleware.proto\x1a#config/transport/v1/transport.proto\"\xf8\x03\n" +
	"\tBootstrap\x12V\n" +
	"\vdiscoveries\x18\x01 \x03(\v24.runtime.test.app.configs.Bootstrap.DiscoveriesEntryR\vdiscoveries\x12>\n" +
	"\x1bregistration_discovery_name\x18\x02 \x01(\tR\x19registrationDiscoveryName\x12A\n" +
	"\aservers\x18\x03 \x03(\v2'.runtime.api.config.transport.v1.ServerR\aservers\x12G\n" +
	"\aclients\x18\x04 \x01(\v2(.runtime.api.config.transport.v1.ClientsH\x00R\aclients\x88\x01\x01\x12O\n" +
	"\vmiddlewares\x18\x05 \x01(\v2-.runtime.api.config.middleware.v1.MiddlewaresR\vmiddlewares\x1aj\n" +
	"\x10DiscoveriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.runtime.api.config.discovery.v1.DiscoveryR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_clientsBCZAgithub.com/origadmin/framework/test/integration/app/proto;configsb\x06proto3"

var (
	file_test_integration_app_proto_bootstrap_proto_rawDescOnce sync.Once
	file_test_integration_app_proto_bootstrap_proto_rawDescData []byte
)

func file_test_integration_app_proto_bootstrap_proto_rawDescGZIP() []byte {
	file_test_integration_app_proto_bootstrap_proto_rawDescOnce.Do(func() {
		file_test_integration_app_proto_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_integration_app_proto_bootstrap_proto_rawDesc), len(file_test_integration_app_proto_bootstrap_proto_rawDesc)))
	})
	return file_test_integration_app_proto_bootstrap_proto_rawDescData
}

var file_test_integration_app_proto_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_integration_app_proto_bootstrap_proto_goTypes = []any{
	(*Bootstrap)(nil),       // 0: runtime.test.app.configs.Bootstrap
	nil,                     // 1: runtime.test.app.configs.Bootstrap.DiscoveriesEntry
	(*v11.Server)(nil),      // 2: runtime.api.config.transport.v1.Server
	(*v11.Clients)(nil),     // 3: runtime.api.config.transport.v1.Clients
	(*v12.Middlewares)(nil), // 4: runtime.api.config.middleware.v1.Middlewares
	(*v1.Discovery)(nil),    // 5: runtime.api.config.discovery.v1.Discovery
}
var file_test_integration_app_proto_bootstrap_proto_depIdxs = []int32{
	1, // 0: runtime.test.app.configs.Bootstrap.discoveries:type_name -> runtime.test.app.configs.Bootstrap.DiscoveriesEntry
	2, // 1: runtime.test.app.configs.Bootstrap.servers:type_name -> runtime.api.config.transport.v1.Server
	3, // 2: runtime.test.app.configs.Bootstrap.clients:type_name -> runtime.api.config.transport.v1.Clients
	4, // 3: runtime.test.app.configs.Bootstrap.middlewares:type_name -> runtime.api.config.middleware.v1.Middlewares
	5, // 4: runtime.test.app.configs.Bootstrap.DiscoveriesEntry.value:type_name -> runtime.api.config.discovery.v1.Discovery
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_test_integration_app_proto_bootstrap_proto_init() }
func file_test_integration_app_proto_bootstrap_proto_init() {
	if File_test_integration_app_proto_bootstrap_proto != nil {
		return
	}
	file_test_integration_app_proto_bootstrap_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_integration_app_proto_bootstrap_proto_rawDesc), len(file_test_integration_app_proto_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_integration_app_proto_bootstrap_proto_goTypes,
		DependencyIndexes: file_test_integration_app_proto_bootstrap_proto_depIdxs,
		MessageInfos:      file_test_integration_app_proto_bootstrap_proto_msgTypes,
	}.Build()
	File_test_integration_app_proto_bootstrap_proto = out.File
	file_test_integration_app_proto_bootstrap_proto_goTypes = nil
	file_test_integration_app_proto_bootstrap_proto_depIdxs = nil
}
