// API Gateway configuration
// This file defines the configuration structure for an API Gateway, including server and downstream client configurations

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: examples/protos/api_gateway/bootstrap.proto

// Package name to prevent naming conflicts

package conf

import (
	v1 "github.com/origadmin/runtime/api/gen/go/runtime/config/v1"
	v11 "github.com/origadmin/runtime/api/gen/go/runtime/discovery/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap is the top-level configuration for an API Gateway
// This configuration initializes an API Gateway service that can provide multiple server interfaces
// and call multiple downstream microservices
type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server configuration list
	// Gateways typically expose multiple server interfaces, for example:
	// - HTTP RESTful API for external access
	// - gRPC interface
	// - WebSocket service
	Servers []*v1.Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	// Downstream client configuration mapping
	// The key is the logical name of the client, used to reference specific clients in code
	// For example:
	// - "user-service-client"
	// - "order-service-client"
	Clients       map[string]*ClientConfig `protobuf:"bytes,2,rep,name=clients,proto3" json:"clients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_examples_protos_api_gateway_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_api_gateway_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_examples_protos_api_gateway_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServers() []*v1.Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Bootstrap) GetClients() map[string]*ClientConfig {
	if x != nil {
		return x.Clients
	}
	return nil
}

// ClientConfig combines all configurations needed for a client
// It includes both business-level and transport-level configurations
// It includes both business-level and transport-level configurations
type ClientConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Business-level client configuration
	// Mainly configures how to discover and select service instances, for example:
	// - Service discovery method (direct, DNS, Consul, etc.)
	// - Load balancing strategy
	// - Circuit breaking and fallback configuration
	Endpoint *v11.Endpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Transport-level client configuration
	// Mainly configures how to communicate with selected service instances, for example:
	// - Communication protocol (HTTP/gRPC)
	// - Timeout settings
	// - Retry policy
	// - TLS configuration
	Transport     *v1.Client `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_examples_protos_api_gateway_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_api_gateway_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_examples_protos_api_gateway_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *ClientConfig) GetEndpoint() *v11.Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *ClientConfig) GetTransport() *v1.Client {
	if x != nil {
		return x.Transport
	}
	return nil
}

var File_examples_protos_api_gateway_bootstrap_proto protoreflect.FileDescriptor

const file_examples_protos_api_gateway_bootstrap_proto_rawDesc = "" +
	"\n" +
	"+examples/protos/api_gateway/bootstrap.proto\x12\x14examples.api_gateway\x1a\x1eruntime/config/v1/server.proto\x1a\x1eruntime/config/v1/client.proto\x1a#runtime/discovery/v1/endpoint.proto\"\xe8\x01\n" +
	"\tBootstrap\x123\n" +
	"\aservers\x18\x01 \x03(\v2\x19.runtime.config.v1.ServerR\aservers\x12F\n" +
	"\aclients\x18\x02 \x03(\v2,.examples.api_gateway.Bootstrap.ClientsEntryR\aclients\x1a^\n" +
	"\fClientsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".examples.api_gateway.ClientConfigR\x05value:\x028\x01\"\x83\x01\n" +
	"\fClientConfig\x12:\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1e.runtime.discovery.v1.EndpointR\bendpoint\x127\n" +
	"\ttransport\x18\x02 \x01(\v2\x19.runtime.config.v1.ClientR\ttransportB\x19Z\x17./api_gateway/conf;confb\x06proto3"

var (
	file_examples_protos_api_gateway_bootstrap_proto_rawDescOnce sync.Once
	file_examples_protos_api_gateway_bootstrap_proto_rawDescData []byte
)

func file_examples_protos_api_gateway_bootstrap_proto_rawDescGZIP() []byte {
	file_examples_protos_api_gateway_bootstrap_proto_rawDescOnce.Do(func() {
		file_examples_protos_api_gateway_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protos_api_gateway_bootstrap_proto_rawDesc), len(file_examples_protos_api_gateway_bootstrap_proto_rawDesc)))
	})
	return file_examples_protos_api_gateway_bootstrap_proto_rawDescData
}

var file_examples_protos_api_gateway_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_examples_protos_api_gateway_bootstrap_proto_goTypes = []any{
	(*Bootstrap)(nil),    // 0: examples.api_gateway.Bootstrap
	(*ClientConfig)(nil), // 1: examples.api_gateway.ClientConfig
	nil,                  // 2: examples.api_gateway.Bootstrap.ClientsEntry
	(*v1.Server)(nil),    // 3: runtime.config.v1.Server
	(*v11.Endpoint)(nil), // 4: runtime.discovery.v1.Endpoint
	(*v1.Client)(nil),    // 5: runtime.config.v1.Client
}
var file_examples_protos_api_gateway_bootstrap_proto_depIdxs = []int32{
	3, // 0: examples.api_gateway.Bootstrap.servers:type_name -> runtime.config.v1.Server
	2, // 1: examples.api_gateway.Bootstrap.clients:type_name -> examples.api_gateway.Bootstrap.ClientsEntry
	4, // 2: examples.api_gateway.ClientConfig.endpoint:type_name -> runtime.discovery.v1.Endpoint
	5, // 3: examples.api_gateway.ClientConfig.transport:type_name -> runtime.config.v1.Client
	1, // 4: examples.api_gateway.Bootstrap.ClientsEntry.value:type_name -> examples.api_gateway.ClientConfig
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_examples_protos_api_gateway_bootstrap_proto_init() }
func file_examples_protos_api_gateway_bootstrap_proto_init() {
	if File_examples_protos_api_gateway_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protos_api_gateway_bootstrap_proto_rawDesc), len(file_examples_protos_api_gateway_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_protos_api_gateway_bootstrap_proto_goTypes,
		DependencyIndexes: file_examples_protos_api_gateway_bootstrap_proto_depIdxs,
		MessageInfos:      file_examples_protos_api_gateway_bootstrap_proto_msgTypes,
	}.Build()
	File_examples_protos_api_gateway_bootstrap_proto = out.File
	file_examples_protos_api_gateway_bootstrap_proto_goTypes = nil
	file_examples_protos_api_gateway_bootstrap_proto_depIdxs = nil
}
