# API Gateway Configuration

# --- Logger Configuration ---
logger:
  level: info
  format: json
  stdout: true
  file:
    path: "output.log"
    max_size: 10 # MB
    max_backups: 3
    max_age: 7 # days
    compress: true

servers:
  # HTTP server for external access
  - http:
      network: tcp
      addr: ":8080"
      timeout: 1s
  # gRPC server for internal access
  - grpc:
      network: tcp
      addr: ":9090"
      timeout: 1s

clients:
  # Configuration for the downstream 'user-service'
  user-service:
    discovery:
      # The name of the service as registered in the discovery service
      name: "user-service"
      # The endpoint format for Kratos service discovery
      endpoint: "discovery:///user-service"
      selector:
        # Use p2c (pick of 2 choices) load balancing
        type: "p2c"
        version: "1.0.0"
    transport:
      # This client communicates via gRPC
      grpc:
        # The target also uses the discovery endpoint
        target: "discovery:///user-service"
        dial_timeout: "2s"

# --- Custom Settings for demonstration ---
custom_settings:
  feature_enabled: true
  api_key: "super-secret-key-123"
  rate_limit: 100
  endpoints:
    - name: "users"
      path: "/api/v1/users"
    - name: "products"
      path: "/api/v1/products"
