# API Gateway Configuration

# --- Logger Configuration ---
logger:
  level: info
  format: json
  stdout: true
  file:
    path: "output.log"
    max_size: 10 # MB
    max_backups: 3
    max_age: 7 # days
    compress: true

servers:
  # HTTP server for external access
  - http:
      network: tcp
      addr: ":8080"
      timeout: 1s
  # gRPC server for internal access
  - grpc:
      network: tcp
      addr: ":9090"
      timeout: 1s

registries:
  discoveries:
    user-service:
      type: "local"
      service_name: "user-service" # Changed from 'name' to 'service_name'

clients:
  # Configuration for the downstream 'user-service'
  user-service:
    discovery:
      name: "user-service"
      endpoint: "discovery:///user-service"
      selector:
        type: "p2c"
        version: "1.0.0"
    transport:
      # This client communicates via gRPC
      grpc:
        # The target also uses the discovery endpoint
        target: "discovery:///user-service"
        dial_timeout: "2s"

# --- Custom Settings for demonstration ---
components:
  my-custom-settings:
    type: "custom_settings"
    feature_enabled: true
    api_key: "super-secret-key-123"
    rate_limit: 100
    endpoints:
      - name: "users"
        path: "/api/v1/users"
      - name: "products"
        path: "/api/v1/products"
