// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: test/integration/config/proto/all_configs.proto

package configs

import (
	v1 "github.com/origadmin/runtime/api/gen/go/runtime/app/v1"
	v11 "github.com/origadmin/runtime/api/gen/go/runtime/bootstrap/v1"
	v12 "github.com/origadmin/runtime/api/gen/go/runtime/config/v1"
	v13 "github.com/origadmin/runtime/api/gen/go/runtime/discovery/v1"
	v14 "github.com/origadmin/runtime/api/gen/go/runtime/extension/v1"
	v15 "github.com/origadmin/runtime/api/gen/go/runtime/logger/v1"
	v16 "github.com/origadmin/runtime/api/gen/go/runtime/middleware/v1"
	v17 "github.com/origadmin/runtime/api/gen/go/runtime/security/authn/v1"
	v18 "github.com/origadmin/runtime/api/gen/go/runtime/security/authz/v1"
	v19 "github.com/origadmin/runtime/api/gen/go/runtime/security/transport/v1"
	v110 "github.com/origadmin/runtime/api/gen/go/runtime/source/v1"
	v111 "github.com/origadmin/runtime/api/gen/go/runtime/storage/v1"
	v112 "github.com/origadmin/runtime/api/gen/go/runtime/task/v1"
	v113 "github.com/origadmin/runtime/api/gen/go/runtime/transport/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Complete configuration test structure
type AllConfigs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// App configuration
	App *v1.App `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// Bootstrap configuration
	Bootstrap *v11.Bootstrap `protobuf:"bytes,2,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	// Config configuration group
	Client    *v12.Client    `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	Gateway   *v12.Gateway   `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Server    *v12.Server    `protobuf:"bytes,5,opt,name=server,proto3" json:"server,omitempty"`
	Storage   *v12.Storage   `protobuf:"bytes,6,opt,name=storage,proto3" json:"storage,omitempty"`
	Task      *v12.Task      `protobuf:"bytes,7,opt,name=task,proto3" json:"task,omitempty"`
	Tracer    *v12.Tracer    `protobuf:"bytes,8,opt,name=tracer,proto3" json:"tracer,omitempty"`
	Websocket *v12.WebSocket `protobuf:"bytes,9,opt,name=websocket,proto3" json:"websocket,omitempty"`
	// Discovery configuration
	Discovery *v13.Discovery `protobuf:"bytes,10,opt,name=discovery,proto3" json:"discovery,omitempty"`
	// Extension configuration
	Extension *v14.Extension `protobuf:"bytes,11,opt,name=extension,proto3" json:"extension,omitempty"`
	// Logger configuration
	Logger *v15.Logger `protobuf:"bytes,12,opt,name=logger,proto3" json:"logger,omitempty"`
	// Middleware configuration
	Middleware *v16.Middleware `protobuf:"bytes,13,opt,name=middleware,proto3" json:"middleware,omitempty"`
	// Security configuration
	Authn *v17.AuthN     `protobuf:"bytes,14,opt,name=authn,proto3" json:"authn,omitempty"`
	Authz *v18.AuthZ     `protobuf:"bytes,15,opt,name=authz,proto3" json:"authz,omitempty"`
	Tls   *v19.TLSConfig `protobuf:"bytes,16,opt,name=tls,proto3" json:"tls,omitempty"`
	// Source configuration
	Sources *v110.Sources `protobuf:"bytes,17,opt,name=sources,proto3" json:"sources,omitempty"`
	// Storage configuration
	StorageV1 *v111.Storage `protobuf:"bytes,18,opt,name=storage_v1,json=storageV1,proto3" json:"storage_v1,omitempty"`
	// Task configuration
	TaskV1 *v112.Task `protobuf:"bytes,19,opt,name=task_v1,json=taskV1,proto3" json:"task_v1,omitempty"`
	// Transport configuration
	Transport     *v113.Transport `protobuf:"bytes,20,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllConfigs) Reset() {
	*x = AllConfigs{}
	mi := &file_test_integration_config_proto_all_configs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllConfigs) ProtoMessage() {}

func (x *AllConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_test_integration_config_proto_all_configs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllConfigs.ProtoReflect.Descriptor instead.
func (*AllConfigs) Descriptor() ([]byte, []int) {
	return file_test_integration_config_proto_all_configs_proto_rawDescGZIP(), []int{0}
}

func (x *AllConfigs) GetApp() *v1.App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *AllConfigs) GetBootstrap() *v11.Bootstrap {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

func (x *AllConfigs) GetClient() *v12.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *AllConfigs) GetGateway() *v12.Gateway {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *AllConfigs) GetServer() *v12.Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *AllConfigs) GetStorage() *v12.Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *AllConfigs) GetTask() *v12.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *AllConfigs) GetTracer() *v12.Tracer {
	if x != nil {
		return x.Tracer
	}
	return nil
}

func (x *AllConfigs) GetWebsocket() *v12.WebSocket {
	if x != nil {
		return x.Websocket
	}
	return nil
}

func (x *AllConfigs) GetDiscovery() *v13.Discovery {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *AllConfigs) GetExtension() *v14.Extension {
	if x != nil {
		return x.Extension
	}
	return nil
}

func (x *AllConfigs) GetLogger() *v15.Logger {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *AllConfigs) GetMiddleware() *v16.Middleware {
	if x != nil {
		return x.Middleware
	}
	return nil
}

func (x *AllConfigs) GetAuthn() *v17.AuthN {
	if x != nil {
		return x.Authn
	}
	return nil
}

func (x *AllConfigs) GetAuthz() *v18.AuthZ {
	if x != nil {
		return x.Authz
	}
	return nil
}

func (x *AllConfigs) GetTls() *v19.TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *AllConfigs) GetSources() *v110.Sources {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *AllConfigs) GetStorageV1() *v111.Storage {
	if x != nil {
		return x.StorageV1
	}
	return nil
}

func (x *AllConfigs) GetTaskV1() *v112.Task {
	if x != nil {
		return x.TaskV1
	}
	return nil
}

func (x *AllConfigs) GetTransport() *v113.Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

var File_test_integration_config_proto_all_configs_proto protoreflect.FileDescriptor

const file_test_integration_config_proto_all_configs_proto_rawDesc = "" +
	"\n" +
	"/test/integration/config/proto/all_configs.proto\x12\ftest.configs\x1a\x18runtime/app/v1/app.proto\x1a$runtime/bootstrap/v1/bootstrap.proto\x1a\x1eruntime/config/v1/client.proto\x1a\x1fruntime/config/v1/gateway.proto\x1a\x1eruntime/config/v1/server.proto\x1a\x1fruntime/config/v1/storage.proto\x1a\x1cruntime/config/v1/task.proto\x1a\x1eruntime/config/v1/tracer.proto\x1a!runtime/config/v1/websocket.proto\x1a$runtime/discovery/v1/discovery.proto\x1a$runtime/extension/v1/extension.proto\x1a\x1eruntime/logger/v1/logger.proto\x1a&runtime/middleware/v1/middleware.proto\x1a%runtime/security/authn/v1/authn.proto\x1a%runtime/security/authz/v1/authz.proto\x1a'runtime/security/transport/v1/tls.proto\x1a\x1eruntime/source/v1/source.proto\x1a runtime/storage/v1/storage.proto\x1a\x1aruntime/task/v1/task.proto\x1a$runtime/transport/v1/transport.proto\"\xe1\b\n" +
	"\n" +
	"AllConfigs\x12%\n" +
	"\x03app\x18\x01 \x01(\v2\x13.runtime.app.v1.AppR\x03app\x12=\n" +
	"\tbootstrap\x18\x02 \x01(\v2\x1f.runtime.bootstrap.v1.BootstrapR\tbootstrap\x121\n" +
	"\x06client\x18\x03 \x01(\v2\x19.runtime.config.v1.ClientR\x06client\x124\n" +
	"\agateway\x18\x04 \x01(\v2\x1a.runtime.config.v1.GatewayR\agateway\x121\n" +
	"\x06server\x18\x05 \x01(\v2\x19.runtime.config.v1.ServerR\x06server\x124\n" +
	"\astorage\x18\x06 \x01(\v2\x1a.runtime.config.v1.StorageR\astorage\x12+\n" +
	"\x04task\x18\a \x01(\v2\x17.runtime.config.v1.TaskR\x04task\x121\n" +
	"\x06tracer\x18\b \x01(\v2\x19.runtime.config.v1.TracerR\x06tracer\x12:\n" +
	"\twebsocket\x18\t \x01(\v2\x1c.runtime.config.v1.WebSocketR\twebsocket\x12=\n" +
	"\tdiscovery\x18\n" +
	" \x01(\v2\x1f.runtime.discovery.v1.DiscoveryR\tdiscovery\x12=\n" +
	"\textension\x18\v \x01(\v2\x1f.runtime.extension.v1.ExtensionR\textension\x121\n" +
	"\x06logger\x18\f \x01(\v2\x19.runtime.logger.v1.LoggerR\x06logger\x12A\n" +
	"\n" +
	"middleware\x18\r \x01(\v2!.runtime.middleware.v1.MiddlewareR\n" +
	"middleware\x126\n" +
	"\x05authn\x18\x0e \x01(\v2 .runtime.security.authn.v1.AuthNR\x05authn\x126\n" +
	"\x05authz\x18\x0f \x01(\v2 .runtime.security.authz.v1.AuthZR\x05authz\x12:\n" +
	"\x03tls\x18\x10 \x01(\v2(.runtime.security.transport.v1.TLSConfigR\x03tls\x124\n" +
	"\asources\x18\x11 \x01(\v2\x1a.runtime.source.v1.SourcesR\asources\x12:\n" +
	"\n" +
	"storage_v1\x18\x12 \x01(\v2\x1b.runtime.storage.v1.StorageR\tstorageV1\x12.\n" +
	"\atask_v1\x18\x13 \x01(\v2\x15.runtime.task.v1.TaskR\x06taskV1\x12=\n" +
	"\ttransport\x18\x14 \x01(\v2\x1f.runtime.transport.v1.TransportR\ttransportBDZBgithub.com/origadmin/runtime/test/integration/config/proto;configsb\x06proto3"

var (
	file_test_integration_config_proto_all_configs_proto_rawDescOnce sync.Once
	file_test_integration_config_proto_all_configs_proto_rawDescData []byte
)

func file_test_integration_config_proto_all_configs_proto_rawDescGZIP() []byte {
	file_test_integration_config_proto_all_configs_proto_rawDescOnce.Do(func() {
		file_test_integration_config_proto_all_configs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_integration_config_proto_all_configs_proto_rawDesc), len(file_test_integration_config_proto_all_configs_proto_rawDesc)))
	})
	return file_test_integration_config_proto_all_configs_proto_rawDescData
}

var file_test_integration_config_proto_all_configs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_integration_config_proto_all_configs_proto_goTypes = []any{
	(*AllConfigs)(nil),     // 0: test.configs.AllConfigs
	(*v1.App)(nil),         // 1: runtime.app.v1.App
	(*v11.Bootstrap)(nil),  // 2: runtime.bootstrap.v1.Bootstrap
	(*v12.Client)(nil),     // 3: runtime.config.v1.Client
	(*v12.Gateway)(nil),    // 4: runtime.config.v1.Gateway
	(*v12.Server)(nil),     // 5: runtime.config.v1.Server
	(*v12.Storage)(nil),    // 6: runtime.config.v1.Storage
	(*v12.Task)(nil),       // 7: runtime.config.v1.Task
	(*v12.Tracer)(nil),     // 8: runtime.config.v1.Tracer
	(*v12.WebSocket)(nil),  // 9: runtime.config.v1.WebSocket
	(*v13.Discovery)(nil),  // 10: runtime.discovery.v1.Discovery
	(*v14.Extension)(nil),  // 11: runtime.extension.v1.Extension
	(*v15.Logger)(nil),     // 12: runtime.logger.v1.Logger
	(*v16.Middleware)(nil), // 13: runtime.middleware.v1.Middleware
	(*v17.AuthN)(nil),      // 14: runtime.security.authn.v1.AuthN
	(*v18.AuthZ)(nil),      // 15: runtime.security.authz.v1.AuthZ
	(*v19.TLSConfig)(nil),  // 16: runtime.security.transport.v1.TLSConfig
	(*v110.Sources)(nil),   // 17: runtime.source.v1.Sources
	(*v111.Storage)(nil),   // 18: runtime.storage.v1.Storage
	(*v112.Task)(nil),      // 19: runtime.task.v1.Task
	(*v113.Transport)(nil), // 20: runtime.transport.v1.Transport
}
var file_test_integration_config_proto_all_configs_proto_depIdxs = []int32{
	1,  // 0: test.configs.AllConfigs.app:type_name -> runtime.app.v1.App
	2,  // 1: test.configs.AllConfigs.bootstrap:type_name -> runtime.bootstrap.v1.Bootstrap
	3,  // 2: test.configs.AllConfigs.client:type_name -> runtime.config.v1.Client
	4,  // 3: test.configs.AllConfigs.gateway:type_name -> runtime.config.v1.Gateway
	5,  // 4: test.configs.AllConfigs.server:type_name -> runtime.config.v1.Server
	6,  // 5: test.configs.AllConfigs.storage:type_name -> runtime.config.v1.Storage
	7,  // 6: test.configs.AllConfigs.task:type_name -> runtime.config.v1.Task
	8,  // 7: test.configs.AllConfigs.tracer:type_name -> runtime.config.v1.Tracer
	9,  // 8: test.configs.AllConfigs.websocket:type_name -> runtime.config.v1.WebSocket
	10, // 9: test.configs.AllConfigs.discovery:type_name -> runtime.discovery.v1.Discovery
	11, // 10: test.configs.AllConfigs.extension:type_name -> runtime.extension.v1.Extension
	12, // 11: test.configs.AllConfigs.logger:type_name -> runtime.logger.v1.Logger
	13, // 12: test.configs.AllConfigs.middleware:type_name -> runtime.middleware.v1.Middleware
	14, // 13: test.configs.AllConfigs.authn:type_name -> runtime.security.authn.v1.AuthN
	15, // 14: test.configs.AllConfigs.authz:type_name -> runtime.security.authz.v1.AuthZ
	16, // 15: test.configs.AllConfigs.tls:type_name -> runtime.security.transport.v1.TLSConfig
	17, // 16: test.configs.AllConfigs.sources:type_name -> runtime.source.v1.Sources
	18, // 17: test.configs.AllConfigs.storage_v1:type_name -> runtime.storage.v1.Storage
	19, // 18: test.configs.AllConfigs.task_v1:type_name -> runtime.task.v1.Task
	20, // 19: test.configs.AllConfigs.transport:type_name -> runtime.transport.v1.Transport
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_test_integration_config_proto_all_configs_proto_init() }
func file_test_integration_config_proto_all_configs_proto_init() {
	if File_test_integration_config_proto_all_configs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_integration_config_proto_all_configs_proto_rawDesc), len(file_test_integration_config_proto_all_configs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_integration_config_proto_all_configs_proto_goTypes,
		DependencyIndexes: file_test_integration_config_proto_all_configs_proto_depIdxs,
		MessageInfos:      file_test_integration_config_proto_all_configs_proto_msgTypes,
	}.Build()
	File_test_integration_config_proto_all_configs_proto = out.File
	file_test_integration_config_proto_all_configs_proto_goTypes = nil
	file_test_integration_config_proto_all_configs_proto_depIdxs = nil
}
