// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: test/integration/config/proto/config.proto

package configs

import (
	v1 "github.com/origadmin/runtime/api/gen/go/runtime/app/v1"
	v14 "github.com/origadmin/runtime/api/gen/go/runtime/config/v1"
	v16 "github.com/origadmin/runtime/api/gen/go/runtime/data/v1"
	v12 "github.com/origadmin/runtime/api/gen/go/runtime/discovery/v1"
	v13 "github.com/origadmin/runtime/api/gen/go/runtime/logger/v1"
	v15 "github.com/origadmin/runtime/api/gen/go/runtime/middleware/v1"
	v19 "github.com/origadmin/runtime/api/gen/go/runtime/security/authn/v1"
	v110 "github.com/origadmin/runtime/api/gen/go/runtime/security/authz/v1"
	v111 "github.com/origadmin/runtime/api/gen/go/runtime/security/transport/v1"
	v17 "github.com/origadmin/runtime/api/gen/go/runtime/task/v1"
	v11 "github.com/origadmin/runtime/api/gen/go/runtime/transport/v1"
	v18 "github.com/origadmin/runtime/api/gen/go/runtime/websocket/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TestConfig is the unified configuration structure for all integration tests.
type TestConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// App configuration from app.proto
	App     *v1.App      `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Servers *v11.Servers `protobuf:"bytes,2,opt,name=servers,proto3" json:"servers,omitempty"`
	Clients *v11.Clients `protobuf:"bytes,3,opt,name=clients,proto3" json:"clients,omitempty"`
	Server  *v11.Server  `protobuf:"bytes,4,opt,name=server,proto3" json:"server,omitempty"`
	Client  *v11.Client  `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	// Service discovery configurations
	Discoveries *v12.Discoveries `protobuf:"bytes,6,opt,name=discoveries,proto3" json:"discoveries,omitempty"`
	Discovery   *v12.Discovery   `protobuf:"bytes,7,opt,name=discovery,proto3" json:"discovery,omitempty"`
	// Service registration configuration
	RegistrationDiscoveryName string `protobuf:"bytes,8,opt,name=registration_discovery_name,json=registrationDiscoveryName,proto3" json:"registration_discovery_name,omitempty"`
	// Other component configurations
	Logger        *v13.Logger      `protobuf:"bytes,9,opt,name=logger,proto3" json:"logger,omitempty"`
	Tracer        *v14.Tracer      `protobuf:"bytes,10,opt,name=tracer,proto3" json:"tracer,omitempty"`
	Middlewares   *v15.Middlewares `protobuf:"bytes,11,opt,name=middlewares,proto3" json:"middlewares,omitempty"`
	Middleware    *v15.Middleware  `protobuf:"bytes,12,opt,name=middleware,proto3" json:"middleware,omitempty"`
	Gateway       *v14.Gateway     `protobuf:"bytes,13,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Data          *v16.Data        `protobuf:"bytes,14,opt,name=data,proto3" json:"data,omitempty"`
	Task          *v17.Task        `protobuf:"bytes,15,opt,name=task,proto3" json:"task,omitempty"`
	Websocket     *v18.WebSocket   `protobuf:"bytes,16,opt,name=websocket,proto3" json:"websocket,omitempty"`
	Authn         *v19.AuthN       `protobuf:"bytes,17,opt,name=authn,proto3" json:"authn,omitempty"`
	Authz         *v110.AuthZ      `protobuf:"bytes,18,opt,name=authz,proto3" json:"authz,omitempty"`
	Tls           *v111.TLSConfig  `protobuf:"bytes,19,opt,name=tls,proto3" json:"tls,omitempty"`
	Customize     *structpb.Struct `protobuf:"bytes,20,opt,name=customize,proto3" json:"customize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConfig) Reset() {
	*x = TestConfig{}
	mi := &file_test_integration_config_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConfig) ProtoMessage() {}

func (x *TestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_test_integration_config_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConfig.ProtoReflect.Descriptor instead.
func (*TestConfig) Descriptor() ([]byte, []int) {
	return file_test_integration_config_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *TestConfig) GetApp() *v1.App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *TestConfig) GetServers() *v11.Servers {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *TestConfig) GetClients() *v11.Clients {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *TestConfig) GetServer() *v11.Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *TestConfig) GetClient() *v11.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *TestConfig) GetDiscoveries() *v12.Discoveries {
	if x != nil {
		return x.Discoveries
	}
	return nil
}

func (x *TestConfig) GetDiscovery() *v12.Discovery {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *TestConfig) GetRegistrationDiscoveryName() string {
	if x != nil {
		return x.RegistrationDiscoveryName
	}
	return ""
}

func (x *TestConfig) GetLogger() *v13.Logger {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *TestConfig) GetTracer() *v14.Tracer {
	if x != nil {
		return x.Tracer
	}
	return nil
}

func (x *TestConfig) GetMiddlewares() *v15.Middlewares {
	if x != nil {
		return x.Middlewares
	}
	return nil
}

func (x *TestConfig) GetMiddleware() *v15.Middleware {
	if x != nil {
		return x.Middleware
	}
	return nil
}

func (x *TestConfig) GetGateway() *v14.Gateway {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *TestConfig) GetData() *v16.Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TestConfig) GetTask() *v17.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *TestConfig) GetWebsocket() *v18.WebSocket {
	if x != nil {
		return x.Websocket
	}
	return nil
}

func (x *TestConfig) GetAuthn() *v19.AuthN {
	if x != nil {
		return x.Authn
	}
	return nil
}

func (x *TestConfig) GetAuthz() *v110.AuthZ {
	if x != nil {
		return x.Authz
	}
	return nil
}

func (x *TestConfig) GetTls() *v111.TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *TestConfig) GetCustomize() *structpb.Struct {
	if x != nil {
		return x.Customize
	}
	return nil
}

var File_test_integration_config_proto_config_proto protoreflect.FileDescriptor

const file_test_integration_config_proto_config_proto_rawDesc = "" +
	"\n" +
	"*test/integration/config/proto/config.proto\x12\ftest.configs\x1a\x1cgoogle/protobuf/struct.proto\x1a\x18runtime/app/v1/app.proto\x1a\x1fruntime/config/v1/gateway.proto\x1a\x1eruntime/config/v1/tracer.proto\x1a\x1aruntime/data/v1/data.proto\x1a$runtime/discovery/v1/discovery.proto\x1a\x1eruntime/logger/v1/logger.proto\x1a&runtime/middleware/v1/middleware.proto\x1a%runtime/security/authn/v1/authn.proto\x1a%runtime/security/authz/v1/authz.proto\x1a'runtime/security/transport/v1/tls.proto\x1a\x1aruntime/task/v1/task.proto\x1a$runtime/transport/v1/transport.proto\x1a$runtime/websocket/v1/websocket.proto\"\xf2\b\n" +
	"\n" +
	"TestConfig\x12%\n" +
	"\x03app\x18\x01 \x01(\v2\x13.runtime.app.v1.AppR\x03app\x127\n" +
	"\aservers\x18\x02 \x01(\v2\x1d.runtime.transport.v1.ServersR\aservers\x127\n" +
	"\aclients\x18\x03 \x01(\v2\x1d.runtime.transport.v1.ClientsR\aclients\x124\n" +
	"\x06server\x18\x04 \x01(\v2\x1c.runtime.transport.v1.ServerR\x06server\x124\n" +
	"\x06client\x18\x05 \x01(\v2\x1c.runtime.transport.v1.ClientR\x06client\x12C\n" +
	"\vdiscoveries\x18\x06 \x01(\v2!.runtime.discovery.v1.DiscoveriesR\vdiscoveries\x12=\n" +
	"\tdiscovery\x18\a \x01(\v2\x1f.runtime.discovery.v1.DiscoveryR\tdiscovery\x12>\n" +
	"\x1bregistration_discovery_name\x18\b \x01(\tR\x19registrationDiscoveryName\x121\n" +
	"\x06logger\x18\t \x01(\v2\x19.runtime.logger.v1.LoggerR\x06logger\x121\n" +
	"\x06tracer\x18\n" +
	" \x01(\v2\x19.runtime.config.v1.TracerR\x06tracer\x12D\n" +
	"\vmiddlewares\x18\v \x01(\v2\".runtime.middleware.v1.MiddlewaresR\vmiddlewares\x12A\n" +
	"\n" +
	"middleware\x18\f \x01(\v2!.runtime.middleware.v1.MiddlewareR\n" +
	"middleware\x124\n" +
	"\agateway\x18\r \x01(\v2\x1a.runtime.config.v1.GatewayR\agateway\x12)\n" +
	"\x04data\x18\x0e \x01(\v2\x15.runtime.data.v1.DataR\x04data\x12)\n" +
	"\x04task\x18\x0f \x01(\v2\x15.runtime.task.v1.TaskR\x04task\x12=\n" +
	"\twebsocket\x18\x10 \x01(\v2\x1f.runtime.websocket.v1.WebSocketR\twebsocket\x126\n" +
	"\x05authn\x18\x11 \x01(\v2 .runtime.security.authn.v1.AuthNR\x05authn\x126\n" +
	"\x05authz\x18\x12 \x01(\v2 .runtime.security.authz.v1.AuthZR\x05authz\x12:\n" +
	"\x03tls\x18\x13 \x01(\v2(.runtime.security.transport.v1.TLSConfigR\x03tls\x125\n" +
	"\tcustomize\x18\x14 \x01(\v2\x17.google.protobuf.StructR\tcustomizeBDZBgithub.com/origadmin/runtime/test/integration/config/proto;configsb\x06proto3"

var (
	file_test_integration_config_proto_config_proto_rawDescOnce sync.Once
	file_test_integration_config_proto_config_proto_rawDescData []byte
)

func file_test_integration_config_proto_config_proto_rawDescGZIP() []byte {
	file_test_integration_config_proto_config_proto_rawDescOnce.Do(func() {
		file_test_integration_config_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_integration_config_proto_config_proto_rawDesc), len(file_test_integration_config_proto_config_proto_rawDesc)))
	})
	return file_test_integration_config_proto_config_proto_rawDescData
}

var file_test_integration_config_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_integration_config_proto_config_proto_goTypes = []any{
	(*TestConfig)(nil),      // 0: test.configs.TestConfig
	(*v1.App)(nil),          // 1: runtime.app.v1.App
	(*v11.Servers)(nil),     // 2: runtime.transport.v1.Servers
	(*v11.Clients)(nil),     // 3: runtime.transport.v1.Clients
	(*v11.Server)(nil),      // 4: runtime.transport.v1.Server
	(*v11.Client)(nil),      // 5: runtime.transport.v1.Client
	(*v12.Discoveries)(nil), // 6: runtime.discovery.v1.Discoveries
	(*v12.Discovery)(nil),   // 7: runtime.discovery.v1.Discovery
	(*v13.Logger)(nil),      // 8: runtime.logger.v1.Logger
	(*v14.Tracer)(nil),      // 9: runtime.config.v1.Tracer
	(*v15.Middlewares)(nil), // 10: runtime.middleware.v1.Middlewares
	(*v15.Middleware)(nil),  // 11: runtime.middleware.v1.Middleware
	(*v14.Gateway)(nil),     // 12: runtime.config.v1.Gateway
	(*v16.Data)(nil),        // 13: runtime.data.v1.Data
	(*v17.Task)(nil),        // 14: runtime.task.v1.Task
	(*v18.WebSocket)(nil),   // 15: runtime.websocket.v1.WebSocket
	(*v19.AuthN)(nil),       // 16: runtime.security.authn.v1.AuthN
	(*v110.AuthZ)(nil),      // 17: runtime.security.authz.v1.AuthZ
	(*v111.TLSConfig)(nil),  // 18: runtime.security.transport.v1.TLSConfig
	(*structpb.Struct)(nil), // 19: google.protobuf.Struct
}
var file_test_integration_config_proto_config_proto_depIdxs = []int32{
	1,  // 0: test.configs.TestConfig.app:type_name -> runtime.app.v1.App
	2,  // 1: test.configs.TestConfig.servers:type_name -> runtime.transport.v1.Servers
	3,  // 2: test.configs.TestConfig.clients:type_name -> runtime.transport.v1.Clients
	4,  // 3: test.configs.TestConfig.server:type_name -> runtime.transport.v1.Server
	5,  // 4: test.configs.TestConfig.client:type_name -> runtime.transport.v1.Client
	6,  // 5: test.configs.TestConfig.discoveries:type_name -> runtime.discovery.v1.Discoveries
	7,  // 6: test.configs.TestConfig.discovery:type_name -> runtime.discovery.v1.Discovery
	8,  // 7: test.configs.TestConfig.logger:type_name -> runtime.logger.v1.Logger
	9,  // 8: test.configs.TestConfig.tracer:type_name -> runtime.config.v1.Tracer
	10, // 9: test.configs.TestConfig.middlewares:type_name -> runtime.middleware.v1.Middlewares
	11, // 10: test.configs.TestConfig.middleware:type_name -> runtime.middleware.v1.Middleware
	12, // 11: test.configs.TestConfig.gateway:type_name -> runtime.config.v1.Gateway
	13, // 12: test.configs.TestConfig.data:type_name -> runtime.data.v1.Data
	14, // 13: test.configs.TestConfig.task:type_name -> runtime.task.v1.Task
	15, // 14: test.configs.TestConfig.websocket:type_name -> runtime.websocket.v1.WebSocket
	16, // 15: test.configs.TestConfig.authn:type_name -> runtime.security.authn.v1.AuthN
	17, // 16: test.configs.TestConfig.authz:type_name -> runtime.security.authz.v1.AuthZ
	18, // 17: test.configs.TestConfig.tls:type_name -> runtime.security.transport.v1.TLSConfig
	19, // 18: test.configs.TestConfig.customize:type_name -> google.protobuf.Struct
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_test_integration_config_proto_config_proto_init() }
func file_test_integration_config_proto_config_proto_init() {
	if File_test_integration_config_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_integration_config_proto_config_proto_rawDesc), len(file_test_integration_config_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_integration_config_proto_config_proto_goTypes,
		DependencyIndexes: file_test_integration_config_proto_config_proto_depIdxs,
		MessageInfos:      file_test_integration_config_proto_config_proto_msgTypes,
	}.Build()
	File_test_integration_config_proto_config_proto = out.File
	file_test_integration_config_proto_config_proto_goTypes = nil
	file_test_integration_config_proto_config_proto_depIdxs = nil
}
