// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from kratos.go.

// Package config contains generated code by adptool.
package config

import (
	config "github.com/go-kratos/kratos/v2/config"
)

var ErrNotFound = config.ErrNotFound

type (
	KConfig   = config.Config
	KDecoder  = config.Decoder
	KKeyValue = config.KeyValue
	KMerge    = config.Merge
	KObserver = config.Observer
	KOption   = config.Option
	KReader   = config.Reader
	KResolver = config.Resolver
	KSource   = config.Source
	KValue    = config.Value
	KWatcher  = config.Watcher
)

func KWithDecoder(d config.Decoder) config.Option {
	return config.WithDecoder(d)
}

func KWithMergeFunc(m config.Merge) config.Option {
	return config.WithMergeFunc(m)
}

func KWithResolveActualTypes(enableConvertToType bool) config.Option {
	return config.WithResolveActualTypes(enableConvertToType)
}

func KWithResolver(r config.Resolver) config.Option {
	return config.WithResolver(r)
}

func KWithSource(s ...config.Source) config.Option {
	return config.WithSource(s...)
}

func NewKConfig(opts ...config.Option) config.Config {
	return config.New(opts...)
}
