// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from kratos.go.

// Package config contains generated code by adptool.
package config

import (
	config "github.com/go-kratos/kratos/v2/config"
	_ "github.com/go-kratos/kratos/v2/encoding/json"
	_ "github.com/go-kratos/kratos/v2/encoding/proto"
	_ "github.com/go-kratos/kratos/v2/encoding/xml"
	_ "github.com/go-kratos/kratos/v2/encoding/yaml"
	// init encoding
)

var ErrNotFound = config.ErrNotFound

type (
	Config   = config.Config
	Decoder  = config.Decoder
	KeyValue = config.KeyValue
	Merge    = config.Merge
	Observer = config.Observer
	Option   = config.Option
	Reader   = config.Reader
	Resolver = config.Resolver
	Source   = config.Source
	Value    = config.Value
	Watcher  = config.Watcher
)

func New(opts ...config.Option) config.Config {
	return config.New(opts...)
}

func WithDecoder(d config.Decoder) config.Option {
	return config.WithDecoder(d)
}

func WithMergeFunc(m config.Merge) config.Option {
	return config.WithMergeFunc(m)
}

func WithResolveActualTypes(enableConvertToType bool) config.Option {
	return config.WithResolveActualTypes(enableConvertToType)
}

func WithResolver(r config.Resolver) config.Option {
	return config.WithResolver(r)
}

func WithSource(s ...config.Source) config.Option {
	return config.WithSource(s...)
}
