// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: examples/protos/load_with_runtime/bootstrap.proto

package conf

import (
	v12 "github.com/origadmin/runtime/api/gen/go/config/discovery/v1"
	v11 "github.com/origadmin/runtime/api/gen/go/config/logger/v1"
	v1 "github.com/origadmin/runtime/api/gen/go/config/transport/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap is the user-facing configuration structure.
// It uses references (like discovery_name) to link configurations.
type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server configurations (e.g., HTTP, gRPC servers)
	Servers []*v1.Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	// Endpoints defines the configuration for all downstream services.
	// The key of the map is the logical name of the endpoint (e.g., "user-service").
	Endpoints map[string]*EndpointConfig `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Logging configuration
	Logger *v11.Logger `protobuf:"bytes,3,opt,name=logger,proto3" json:"logger,omitempty"`
	// RegistriesConfig holds the definitions of available discovery service providers.
	Discoveries   map[string]*v12.Discovery `protobuf:"bytes,4,rep,name=discoveries,proto3" json:"discoveries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_examples_protos_load_with_runtime_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServers() []*v1.Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Bootstrap) GetEndpoints() map[string]*EndpointConfig {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Bootstrap) GetLogger() *v11.Logger {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *Bootstrap) GetDiscoveries() map[string]*v12.Discovery {
	if x != nil {
		return x.Discoveries
	}
	return nil
}

// EndpointConfig represents the user-facing configuration for an endpoint.
// It uses a string reference (`discovery_name`) to link to a discovery provider.
type EndpointConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the discovery provider configuration (from registries.discoveries) to use.
	DiscoveryName string `protobuf:"bytes,1,opt,name=discovery_name,proto3" json:"discovery_name,omitempty"`
	// The endpoint URI to connect to, e.g., "discovery:///user-service".
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	// Selector for client-side load balancing and node filtering.
	Selector *EndpointConfig_Selector `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	// Transport configuration for this client.
	Client        *v1.Client `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointConfig) Reset() {
	*x = EndpointConfig{}
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointConfig) ProtoMessage() {}

func (x *EndpointConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointConfig.ProtoReflect.Descriptor instead.
func (*EndpointConfig) Descriptor() ([]byte, []int) {
	return file_examples_protos_load_with_runtime_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointConfig) GetDiscoveryName() string {
	if x != nil {
		return x.DiscoveryName
	}
	return ""
}

func (x *EndpointConfig) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *EndpointConfig) GetSelector() *EndpointConfig_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *EndpointConfig) GetClient() *v1.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// We need to define Selector here as it was in the old client.proto/endpoint.proto
type EndpointConfig_Selector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointConfig_Selector) Reset() {
	*x = EndpointConfig_Selector{}
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointConfig_Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointConfig_Selector) ProtoMessage() {}

func (x *EndpointConfig_Selector) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointConfig_Selector.ProtoReflect.Descriptor instead.
func (*EndpointConfig_Selector) Descriptor() ([]byte, []int) {
	return file_examples_protos_load_with_runtime_bootstrap_proto_rawDescGZIP(), []int{1, 0}
}

func (x *EndpointConfig_Selector) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EndpointConfig_Selector) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_examples_protos_load_with_runtime_bootstrap_proto protoreflect.FileDescriptor

const file_examples_protos_load_with_runtime_bootstrap_proto_rawDesc = "" +
	"\n" +
	"1examples/protos/load_with_runtime/bootstrap.proto\x12\"runtime.examples.load_with_runtime\x1a#config/discovery/v1/discovery.proto\x1a\x1dconfig/logger/v1/logger.proto\x1a#config/transport/v1/transport.proto\"\xa8\x04\n" +
	"\tBootstrap\x12A\n" +
	"\aservers\x18\x01 \x03(\v2'.runtime.api.config.transport.v1.ServerR\aservers\x12Z\n" +
	"\tendpoints\x18\x02 \x03(\v2<.runtime.examples.load_with_runtime.Bootstrap.EndpointsEntryR\tendpoints\x12<\n" +
	"\x06logger\x18\x03 \x01(\v2$.runtime.api.config.logger.v1.LoggerR\x06logger\x12`\n" +
	"\vdiscoveries\x18\x04 \x03(\v2>.runtime.examples.load_with_runtime.Bootstrap.DiscoveriesEntryR\vdiscoveries\x1ap\n" +
	"\x0eEndpointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12H\n" +
	"\x05value\x18\x02 \x01(\v22.runtime.examples.load_with_runtime.EndpointConfigR\x05value:\x028\x01\x1aj\n" +
	"\x10DiscoveriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.runtime.api.config.discovery.v1.DiscoveryR\x05value:\x028\x01\"\x9e\x02\n" +
	"\x0eEndpointConfig\x12&\n" +
	"\x0ediscovery_name\x18\x01 \x01(\tR\x0ediscovery_name\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12W\n" +
	"\bselector\x18\x03 \x01(\v2;.runtime.examples.load_with_runtime.EndpointConfig.SelectorR\bselector\x12?\n" +
	"\x06client\x18\x04 \x01(\v2'.runtime.api.config.transport.v1.ClientR\x06client\x1a8\n" +
	"\bSelector\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversionB\x1fZ\x1d./load_with_runtime/conf;confb\x06proto3"

var (
	file_examples_protos_load_with_runtime_bootstrap_proto_rawDescOnce sync.Once
	file_examples_protos_load_with_runtime_bootstrap_proto_rawDescData []byte
)

func file_examples_protos_load_with_runtime_bootstrap_proto_rawDescGZIP() []byte {
	file_examples_protos_load_with_runtime_bootstrap_proto_rawDescOnce.Do(func() {
		file_examples_protos_load_with_runtime_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protos_load_with_runtime_bootstrap_proto_rawDesc), len(file_examples_protos_load_with_runtime_bootstrap_proto_rawDesc)))
	})
	return file_examples_protos_load_with_runtime_bootstrap_proto_rawDescData
}

var file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_examples_protos_load_with_runtime_bootstrap_proto_goTypes = []any{
	(*Bootstrap)(nil),               // 0: runtime.examples.load_with_runtime.Bootstrap
	(*EndpointConfig)(nil),          // 1: runtime.examples.load_with_runtime.EndpointConfig
	nil,                             // 2: runtime.examples.load_with_runtime.Bootstrap.EndpointsEntry
	nil,                             // 3: runtime.examples.load_with_runtime.Bootstrap.DiscoveriesEntry
	(*EndpointConfig_Selector)(nil), // 4: runtime.examples.load_with_runtime.EndpointConfig.Selector
	(*v1.Server)(nil),               // 5: runtime.api.config.transport.v1.Server
	(*v11.Logger)(nil),              // 6: runtime.api.config.logger.v1.Logger
	(*v1.Client)(nil),               // 7: runtime.api.config.transport.v1.Client
	(*v12.Discovery)(nil),           // 8: runtime.api.config.discovery.v1.Discovery
}
var file_examples_protos_load_with_runtime_bootstrap_proto_depIdxs = []int32{
	5, // 0: runtime.examples.load_with_runtime.Bootstrap.servers:type_name -> runtime.api.config.transport.v1.Server
	2, // 1: runtime.examples.load_with_runtime.Bootstrap.endpoints:type_name -> runtime.examples.load_with_runtime.Bootstrap.EndpointsEntry
	6, // 2: runtime.examples.load_with_runtime.Bootstrap.logger:type_name -> runtime.api.config.logger.v1.Logger
	3, // 3: runtime.examples.load_with_runtime.Bootstrap.discoveries:type_name -> runtime.examples.load_with_runtime.Bootstrap.DiscoveriesEntry
	4, // 4: runtime.examples.load_with_runtime.EndpointConfig.selector:type_name -> runtime.examples.load_with_runtime.EndpointConfig.Selector
	7, // 5: runtime.examples.load_with_runtime.EndpointConfig.client:type_name -> runtime.api.config.transport.v1.Client
	1, // 6: runtime.examples.load_with_runtime.Bootstrap.EndpointsEntry.value:type_name -> runtime.examples.load_with_runtime.EndpointConfig
	8, // 7: runtime.examples.load_with_runtime.Bootstrap.DiscoveriesEntry.value:type_name -> runtime.api.config.discovery.v1.Discovery
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_examples_protos_load_with_runtime_bootstrap_proto_init() }
func file_examples_protos_load_with_runtime_bootstrap_proto_init() {
	if File_examples_protos_load_with_runtime_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protos_load_with_runtime_bootstrap_proto_rawDesc), len(file_examples_protos_load_with_runtime_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_protos_load_with_runtime_bootstrap_proto_goTypes,
		DependencyIndexes: file_examples_protos_load_with_runtime_bootstrap_proto_depIdxs,
		MessageInfos:      file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes,
	}.Build()
	File_examples_protos_load_with_runtime_bootstrap_proto = out.File
	file_examples_protos_load_with_runtime_bootstrap_proto_goTypes = nil
	file_examples_protos_load_with_runtime_bootstrap_proto_depIdxs = nil
}
