// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: protos/load_with_runtime/bootstrap.proto

package conf

import (
	v12 "github.com/origadmin/runtime/api/gen/go/discovery/v1"
	v11 "github.com/origadmin/runtime/api/gen/go/logger/v1"
	v1 "github.com/origadmin/runtime/api/gen/go/transport/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap is the top-level configuration for a rich example application,
// composed of existing framework API protos.
type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server configurations (e.g., HTTP, gRPC servers)
	Servers []*v1.Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	// Downstream client configurations
	Clients map[string]*ClientConfig `protobuf:"bytes,2,rep,name=clients,proto3" json:"clients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Logging configuration
	Logger *v11.Logger `protobuf:"bytes,3,opt,name=logger,proto3" json:"logger,omitempty"` // Use the existing logger proto
	// Registries configuration, including service discoveries
	Registries    *RegistriesConfig `protobuf:"bytes,4,opt,name=registries,proto3" json:"registries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_protos_load_with_runtime_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_protos_load_with_runtime_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_protos_load_with_runtime_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServers() []*v1.Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Bootstrap) GetClients() map[string]*ClientConfig {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *Bootstrap) GetLogger() *v11.Logger {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *Bootstrap) GetRegistries() *RegistriesConfig {
	if x != nil {
		return x.Registries
	}
	return nil
}

// ClientConfig combines all configurations needed for a client
type ClientConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Discovery     *v12.Client            `protobuf:"bytes,1,opt,name=discovery,proto3" json:"discovery,omitempty"`
	Transport     *v1.Client             `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_protos_load_with_runtime_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protos_load_with_runtime_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_protos_load_with_runtime_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *ClientConfig) GetDiscovery() *v12.Client {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *ClientConfig) GetTransport() *v1.Client {
	if x != nil {
		return x.Transport
	}
	return nil
}

// RegistriesConfig holds various registry-related configurations.
type RegistriesConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service discovery configurations
	Discoveries   map[string]*v12.Discovery `protobuf:"bytes,1,rep,name=discoveries,proto3" json:"discoveries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistriesConfig) Reset() {
	*x = RegistriesConfig{}
	mi := &file_protos_load_with_runtime_bootstrap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistriesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistriesConfig) ProtoMessage() {}

func (x *RegistriesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protos_load_with_runtime_bootstrap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistriesConfig.ProtoReflect.Descriptor instead.
func (*RegistriesConfig) Descriptor() ([]byte, []int) {
	return file_protos_load_with_runtime_bootstrap_proto_rawDescGZIP(), []int{2}
}

func (x *RegistriesConfig) GetDiscoveries() map[string]*v12.Discovery {
	if x != nil {
		return x.Discoveries
	}
	return nil
}

var File_protos_load_with_runtime_bootstrap_proto protoreflect.FileDescriptor

const file_protos_load_with_runtime_bootstrap_proto_rawDesc = "" +
	"\n" +
	"(protos/load_with_runtime/bootstrap.proto\x12\x1aexamples.load_with_runtime\x1a\x19discovery/v1/client.proto\x1a\x1cdiscovery/v1/discovery.proto\x1a\x16logger/v1/logger.proto\x1a\x19transport/v1/client.proto\x1a\x19transport/v1/server.proto\"\xe8\x02\n" +
	"\tBootstrap\x12.\n" +
	"\aservers\x18\x01 \x03(\v2\x14.transport.v1.ServerR\aservers\x12L\n" +
	"\aclients\x18\x02 \x03(\v22.examples.load_with_runtime.Bootstrap.ClientsEntryR\aclients\x12)\n" +
	"\x06logger\x18\x03 \x01(\v2\x11.logger.v1.LoggerR\x06logger\x12L\n" +
	"\n" +
	"registries\x18\x04 \x01(\v2,.examples.load_with_runtime.RegistriesConfigR\n" +
	"registries\x1ad\n" +
	"\fClientsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.examples.load_with_runtime.ClientConfigR\x05value:\x028\x01\"v\n" +
	"\fClientConfig\x122\n" +
	"\tdiscovery\x18\x01 \x01(\v2\x14.discovery.v1.ClientR\tdiscovery\x122\n" +
	"\ttransport\x18\x02 \x01(\v2\x14.transport.v1.ClientR\ttransport\"\xcc\x01\n" +
	"\x10RegistriesConfig\x12_\n" +
	"\vdiscoveries\x18\x01 \x03(\v2=.examples.load_with_runtime.RegistriesConfig.DiscoveriesEntryR\vdiscoveries\x1aW\n" +
	"\x10DiscoveriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.discovery.v1.DiscoveryR\x05value:\x028\x01B\x1fZ\x1d./load_with_runtime/conf;confb\x06proto3"

var (
	file_protos_load_with_runtime_bootstrap_proto_rawDescOnce sync.Once
	file_protos_load_with_runtime_bootstrap_proto_rawDescData []byte
)

func file_protos_load_with_runtime_bootstrap_proto_rawDescGZIP() []byte {
	file_protos_load_with_runtime_bootstrap_proto_rawDescOnce.Do(func() {
		file_protos_load_with_runtime_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_load_with_runtime_bootstrap_proto_rawDesc), len(file_protos_load_with_runtime_bootstrap_proto_rawDesc)))
	})
	return file_protos_load_with_runtime_bootstrap_proto_rawDescData
}

var file_protos_load_with_runtime_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_load_with_runtime_bootstrap_proto_goTypes = []any{
	(*Bootstrap)(nil),        // 0: examples.load_with_runtime.Bootstrap
	(*ClientConfig)(nil),     // 1: examples.load_with_runtime.ClientConfig
	(*RegistriesConfig)(nil), // 2: examples.load_with_runtime.RegistriesConfig
	nil,                      // 3: examples.load_with_runtime.Bootstrap.ClientsEntry
	nil,                      // 4: examples.load_with_runtime.RegistriesConfig.DiscoveriesEntry
	(*v1.Server)(nil),        // 5: transport.v1.Server
	(*v11.Logger)(nil),       // 6: logger.v1.Logger
	(*v12.Client)(nil),       // 7: discovery.v1.Client
	(*v1.Client)(nil),        // 8: transport.v1.Client
	(*v12.Discovery)(nil),    // 9: discovery.v1.Discovery
}
var file_protos_load_with_runtime_bootstrap_proto_depIdxs = []int32{
	5, // 0: examples.load_with_runtime.Bootstrap.servers:type_name -> transport.v1.Server
	3, // 1: examples.load_with_runtime.Bootstrap.clients:type_name -> examples.load_with_runtime.Bootstrap.ClientsEntry
	6, // 2: examples.load_with_runtime.Bootstrap.logger:type_name -> logger.v1.Logger
	2, // 3: examples.load_with_runtime.Bootstrap.registries:type_name -> examples.load_with_runtime.RegistriesConfig
	7, // 4: examples.load_with_runtime.ClientConfig.discovery:type_name -> discovery.v1.Client
	8, // 5: examples.load_with_runtime.ClientConfig.transport:type_name -> transport.v1.Client
	4, // 6: examples.load_with_runtime.RegistriesConfig.discoveries:type_name -> examples.load_with_runtime.RegistriesConfig.DiscoveriesEntry
	1, // 7: examples.load_with_runtime.Bootstrap.ClientsEntry.value:type_name -> examples.load_with_runtime.ClientConfig
	9, // 8: examples.load_with_runtime.RegistriesConfig.DiscoveriesEntry.value:type_name -> discovery.v1.Discovery
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_protos_load_with_runtime_bootstrap_proto_init() }
func file_protos_load_with_runtime_bootstrap_proto_init() {
	if File_protos_load_with_runtime_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_load_with_runtime_bootstrap_proto_rawDesc), len(file_protos_load_with_runtime_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_load_with_runtime_bootstrap_proto_goTypes,
		DependencyIndexes: file_protos_load_with_runtime_bootstrap_proto_depIdxs,
		MessageInfos:      file_protos_load_with_runtime_bootstrap_proto_msgTypes,
	}.Build()
	File_protos_load_with_runtime_bootstrap_proto = out.File
	file_protos_load_with_runtime_bootstrap_proto_goTypes = nil
	file_protos_load_with_runtime_bootstrap_proto_depIdxs = nil
}
