// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: examples/protos/load_with_runtime/bootstrap.proto

package conf

import (
	v1 "github.com/origadmin/runtime/api/gen/go/runtime/config/v1"
	v12 "github.com/origadmin/runtime/api/gen/go/runtime/discovery/v1"
	v11 "github.com/origadmin/runtime/api/gen/go/runtime/logger/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap is the user-facing configuration structure.
// It uses references (like discovery_name) to link configurations.
type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server configurations (e.g., HTTP, gRPC servers)
	Servers []*v1.Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	// Endpoints defines the configuration for all downstream services.
	// The key of the map is the logical name of the endpoint (e.g., "user-service").
	Endpoints map[string]*EndpointConfig `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Logging configuration
	Logger *v11.Logger `protobuf:"bytes,3,opt,name=logger,proto3" json:"logger,omitempty"`
	// RegistriesConfig holds the definitions of available discovery service providers.
	Registries    *RegistriesConfig `protobuf:"bytes,4,opt,name=registries,proto3" json:"registries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_examples_protos_load_with_runtime_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServers() []*v1.Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Bootstrap) GetEndpoints() map[string]*EndpointConfig {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Bootstrap) GetLogger() *v11.Logger {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *Bootstrap) GetRegistries() *RegistriesConfig {
	if x != nil {
		return x.Registries
	}
	return nil
}

// EndpointConfig represents the user-facing configuration for an endpoint.
// It uses a string reference (`discovery_name`) to link to a discovery provider.
type EndpointConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the discovery provider configuration (from registries.discoveries) to use.
	DiscoveryName string `protobuf:"bytes,1,opt,name=discovery_name,proto3" json:"discovery_name,omitempty"`
	// The endpoint URI to connect to, e.g., "discovery:///user-service".
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	// Selector for client-side load balancing and node filtering.
	Selector *EndpointConfig_Selector `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	// Transport configuration for this client.
	Transport     *v1.Client `protobuf:"bytes,4,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointConfig) Reset() {
	*x = EndpointConfig{}
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointConfig) ProtoMessage() {}

func (x *EndpointConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointConfig.ProtoReflect.Descriptor instead.
func (*EndpointConfig) Descriptor() ([]byte, []int) {
	return file_examples_protos_load_with_runtime_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointConfig) GetDiscoveryName() string {
	if x != nil {
		return x.DiscoveryName
	}
	return ""
}

func (x *EndpointConfig) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *EndpointConfig) GetSelector() *EndpointConfig_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *EndpointConfig) GetTransport() *v1.Client {
	if x != nil {
		return x.Transport
	}
	return nil
}

// RegistriesConfig holds the definitions of available discovery service providers.
type RegistriesConfig struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Discoveries   map[string]*v12.Discovery `protobuf:"bytes,1,rep,name=discoveries,proto3" json:"discoveries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistriesConfig) Reset() {
	*x = RegistriesConfig{}
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistriesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistriesConfig) ProtoMessage() {}

func (x *RegistriesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistriesConfig.ProtoReflect.Descriptor instead.
func (*RegistriesConfig) Descriptor() ([]byte, []int) {
	return file_examples_protos_load_with_runtime_bootstrap_proto_rawDescGZIP(), []int{2}
}

func (x *RegistriesConfig) GetDiscoveries() map[string]*v12.Discovery {
	if x != nil {
		return x.Discoveries
	}
	return nil
}

// We need to define Selector here as it was in the old client.proto/endpoint.proto
type EndpointConfig_Selector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointConfig_Selector) Reset() {
	*x = EndpointConfig_Selector{}
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointConfig_Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointConfig_Selector) ProtoMessage() {}

func (x *EndpointConfig_Selector) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointConfig_Selector.ProtoReflect.Descriptor instead.
func (*EndpointConfig_Selector) Descriptor() ([]byte, []int) {
	return file_examples_protos_load_with_runtime_bootstrap_proto_rawDescGZIP(), []int{1, 0}
}

func (x *EndpointConfig_Selector) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EndpointConfig_Selector) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_examples_protos_load_with_runtime_bootstrap_proto protoreflect.FileDescriptor

const file_examples_protos_load_with_runtime_bootstrap_proto_rawDesc = "" +
	"\n" +
	"1examples/protos/load_with_runtime/bootstrap.proto\x12\x1aexamples.load_with_runtime\x1a$runtime/discovery/v1/discovery.proto\x1a\x1eruntime/logger/v1/logger.proto\x1a\x1eruntime/config/v1/client.proto\x1a\x1eruntime/config/v1/server.proto\"\xff\x02\n" +
	"\tBootstrap\x123\n" +
	"\aservers\x18\x01 \x03(\v2\x19.runtime.config.v1.ServerR\aservers\x12R\n" +
	"\tendpoints\x18\x02 \x03(\v24.examples.load_with_runtime.Bootstrap.EndpointsEntryR\tendpoints\x121\n" +
	"\x06logger\x18\x03 \x01(\v2\x19.runtime.logger.v1.LoggerR\x06logger\x12L\n" +
	"\n" +
	"registries\x18\x04 \x01(\v2,.examples.load_with_runtime.RegistriesConfigR\n" +
	"registries\x1ah\n" +
	"\x0eEndpointsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.examples.load_with_runtime.EndpointConfigR\x05value:\x028\x01\"\x8e\x02\n" +
	"\x0eEndpointConfig\x12&\n" +
	"\x0ediscovery_name\x18\x01 \x01(\tR\x0ediscovery_name\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12O\n" +
	"\bselector\x18\x03 \x01(\v23.examples.load_with_runtime.EndpointConfig.SelectorR\bselector\x127\n" +
	"\ttransport\x18\x04 \x01(\v2\x19.runtime.config.v1.ClientR\ttransport\x1a8\n" +
	"\bSelector\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xd4\x01\n" +
	"\x10RegistriesConfig\x12_\n" +
	"\vdiscoveries\x18\x01 \x03(\v2=.examples.load_with_runtime.RegistriesConfig.DiscoveriesEntryR\vdiscoveries\x1a_\n" +
	"\x10DiscoveriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.runtime.discovery.v1.DiscoveryR\x05value:\x028\x01B\x1fZ\x1d./load_with_runtime/conf;confb\x06proto3"

var (
	file_examples_protos_load_with_runtime_bootstrap_proto_rawDescOnce sync.Once
	file_examples_protos_load_with_runtime_bootstrap_proto_rawDescData []byte
)

func file_examples_protos_load_with_runtime_bootstrap_proto_rawDescGZIP() []byte {
	file_examples_protos_load_with_runtime_bootstrap_proto_rawDescOnce.Do(func() {
		file_examples_protos_load_with_runtime_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protos_load_with_runtime_bootstrap_proto_rawDesc), len(file_examples_protos_load_with_runtime_bootstrap_proto_rawDesc)))
	})
	return file_examples_protos_load_with_runtime_bootstrap_proto_rawDescData
}

var file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_examples_protos_load_with_runtime_bootstrap_proto_goTypes = []any{
	(*Bootstrap)(nil),               // 0: examples.load_with_runtime.Bootstrap
	(*EndpointConfig)(nil),          // 1: examples.load_with_runtime.EndpointConfig
	(*RegistriesConfig)(nil),        // 2: examples.load_with_runtime.RegistriesConfig
	nil,                             // 3: examples.load_with_runtime.Bootstrap.EndpointsEntry
	(*EndpointConfig_Selector)(nil), // 4: examples.load_with_runtime.EndpointConfig.Selector
	nil,                             // 5: examples.load_with_runtime.RegistriesConfig.DiscoveriesEntry
	(*v1.Server)(nil),               // 6: runtime.config.v1.Server
	(*v11.Logger)(nil),              // 7: runtime.logger.v1.Logger
	(*v1.Client)(nil),               // 8: runtime.config.v1.Client
	(*v12.Discovery)(nil),           // 9: runtime.discovery.v1.Discovery
}
var file_examples_protos_load_with_runtime_bootstrap_proto_depIdxs = []int32{
	6, // 0: examples.load_with_runtime.Bootstrap.servers:type_name -> runtime.config.v1.Server
	3, // 1: examples.load_with_runtime.Bootstrap.endpoints:type_name -> examples.load_with_runtime.Bootstrap.EndpointsEntry
	7, // 2: examples.load_with_runtime.Bootstrap.logger:type_name -> runtime.logger.v1.Logger
	2, // 3: examples.load_with_runtime.Bootstrap.registries:type_name -> examples.load_with_runtime.RegistriesConfig
	4, // 4: examples.load_with_runtime.EndpointConfig.selector:type_name -> examples.load_with_runtime.EndpointConfig.Selector
	8, // 5: examples.load_with_runtime.EndpointConfig.transport:type_name -> runtime.config.v1.Client
	5, // 6: examples.load_with_runtime.RegistriesConfig.discoveries:type_name -> examples.load_with_runtime.RegistriesConfig.DiscoveriesEntry
	1, // 7: examples.load_with_runtime.Bootstrap.EndpointsEntry.value:type_name -> examples.load_with_runtime.EndpointConfig
	9, // 8: examples.load_with_runtime.RegistriesConfig.DiscoveriesEntry.value:type_name -> runtime.discovery.v1.Discovery
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_examples_protos_load_with_runtime_bootstrap_proto_init() }
func file_examples_protos_load_with_runtime_bootstrap_proto_init() {
	if File_examples_protos_load_with_runtime_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protos_load_with_runtime_bootstrap_proto_rawDesc), len(file_examples_protos_load_with_runtime_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_protos_load_with_runtime_bootstrap_proto_goTypes,
		DependencyIndexes: file_examples_protos_load_with_runtime_bootstrap_proto_depIdxs,
		MessageInfos:      file_examples_protos_load_with_runtime_bootstrap_proto_msgTypes,
	}.Build()
	File_examples_protos_load_with_runtime_bootstrap_proto = out.File
	file_examples_protos_load_with_runtime_bootstrap_proto_goTypes = nil
	file_examples_protos_load_with_runtime_bootstrap_proto_depIdxs = nil
}
