// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from kratos.go.

// Package middleware contains generated code by adptool.
package middleware

import (
	"github.com/go-kratos/kratos/v2/middleware"
)

type (
	KHandler    = middleware.Handler
	KMiddleware = middleware.Middleware
)

func KChain(m ...middleware.Middleware) middleware.Middleware {
	return middleware.Chain(m...)
}
