// Code generated by adptool. DO NOT EDIT.
//
// This file is generated from kratos.go.

// Package middleware contains generated code by adptool.
package middleware

import (
	middleware "github.com/go-kratos/kratos/v2/middleware"
)

type (
	KratosHandler    = middleware.Handler
	KratosMiddleware = middleware.Middleware
)

func Chain(m ...middleware.Middleware) middleware.Middleware {
	return middleware.Chain(m...)
}
