// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: examples/protos/custom_extension_example/custom_config.proto

package conf

import (
	v1 "github.com/origadmin/runtime/api/gen/go/runtime/extension/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Custom configuration message
type CustomConfig struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	CustomField   string                     `protobuf:"bytes,1,opt,name=custom_field,json=customField,proto3" json:"custom_field,omitempty"`
	CustomNumber  int32                      `protobuf:"varint,2,opt,name=custom_number,json=customNumber,proto3" json:"custom_number,omitempty"`
	Items         []string                   `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Nested        *CustomConfig_NestedConfig `protobuf:"bytes,4,opt,name=nested,proto3" json:"nested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomConfig) Reset() {
	*x = CustomConfig{}
	mi := &file_examples_protos_custom_extension_example_custom_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomConfig) ProtoMessage() {}

func (x *CustomConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_custom_extension_example_custom_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomConfig.ProtoReflect.Descriptor instead.
func (*CustomConfig) Descriptor() ([]byte, []int) {
	return file_examples_protos_custom_extension_example_custom_config_proto_rawDescGZIP(), []int{0}
}

func (x *CustomConfig) GetCustomField() string {
	if x != nil {
		return x.CustomField
	}
	return ""
}

func (x *CustomConfig) GetCustomNumber() int32 {
	if x != nil {
		return x.CustomNumber
	}
	return 0
}

func (x *CustomConfig) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CustomConfig) GetNested() *CustomConfig_NestedConfig {
	if x != nil {
		return x.Nested
	}
	return nil
}

// Application configuration
type ApplicationConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Use ExtensionMap to hold framework configurations
	Customize     *v1.CustomizeConfig `protobuf:"bytes,1,opt,name=customize,proto3" json:"customize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationConfig) Reset() {
	*x = ApplicationConfig{}
	mi := &file_examples_protos_custom_extension_example_custom_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfig) ProtoMessage() {}

func (x *ApplicationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_custom_extension_example_custom_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfig.ProtoReflect.Descriptor instead.
func (*ApplicationConfig) Descriptor() ([]byte, []int) {
	return file_examples_protos_custom_extension_example_custom_config_proto_rawDescGZIP(), []int{1}
}

func (x *ApplicationConfig) GetCustomize() *v1.CustomizeConfig {
	if x != nil {
		return x.Customize
	}
	return nil
}

type CustomConfig_NestedConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomConfig_NestedConfig) Reset() {
	*x = CustomConfig_NestedConfig{}
	mi := &file_examples_protos_custom_extension_example_custom_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomConfig_NestedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomConfig_NestedConfig) ProtoMessage() {}

func (x *CustomConfig_NestedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_custom_extension_example_custom_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomConfig_NestedConfig.ProtoReflect.Descriptor instead.
func (*CustomConfig_NestedConfig) Descriptor() ([]byte, []int) {
	return file_examples_protos_custom_extension_example_custom_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CustomConfig_NestedConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CustomConfig_NestedConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_examples_protos_custom_extension_example_custom_config_proto protoreflect.FileDescriptor

const file_examples_protos_custom_extension_example_custom_config_proto_rawDesc = "" +
	"\n" +
	"<examples/protos/custom_extension_example/custom_config.proto\x12!examples.custom_extension_example\x1a$runtime/extension/v1/extension.proto\"\x80\x02\n" +
	"\fCustomConfig\x12!\n" +
	"\fcustom_field\x18\x01 \x01(\tR\vcustomField\x12#\n" +
	"\rcustom_number\x18\x02 \x01(\x05R\fcustomNumber\x12\x14\n" +
	"\x05items\x18\x03 \x03(\tR\x05items\x12T\n" +
	"\x06nested\x18\x04 \x01(\v2<.examples.custom_extension_example.CustomConfig.NestedConfigR\x06nested\x1a<\n" +
	"\fNestedConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"X\n" +
	"\x11ApplicationConfig\x12C\n" +
	"\tcustomize\x18\x01 \x01(\v2%.runtime.extension.v1.CustomizeConfigR\tcustomizeB&Z$./custom_extension_example/conf;confb\x06proto3"

var (
	file_examples_protos_custom_extension_example_custom_config_proto_rawDescOnce sync.Once
	file_examples_protos_custom_extension_example_custom_config_proto_rawDescData []byte
)

func file_examples_protos_custom_extension_example_custom_config_proto_rawDescGZIP() []byte {
	file_examples_protos_custom_extension_example_custom_config_proto_rawDescOnce.Do(func() {
		file_examples_protos_custom_extension_example_custom_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protos_custom_extension_example_custom_config_proto_rawDesc), len(file_examples_protos_custom_extension_example_custom_config_proto_rawDesc)))
	})
	return file_examples_protos_custom_extension_example_custom_config_proto_rawDescData
}

var file_examples_protos_custom_extension_example_custom_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_examples_protos_custom_extension_example_custom_config_proto_goTypes = []any{
	(*CustomConfig)(nil),              // 0: examples.custom_extension_example.CustomConfig
	(*ApplicationConfig)(nil),         // 1: examples.custom_extension_example.ApplicationConfig
	(*CustomConfig_NestedConfig)(nil), // 2: examples.custom_extension_example.CustomConfig.NestedConfig
	(*v1.CustomizeConfig)(nil),        // 3: runtime.extension.v1.CustomizeConfig
}
var file_examples_protos_custom_extension_example_custom_config_proto_depIdxs = []int32{
	2, // 0: examples.custom_extension_example.CustomConfig.nested:type_name -> examples.custom_extension_example.CustomConfig.NestedConfig
	3, // 1: examples.custom_extension_example.ApplicationConfig.customize:type_name -> runtime.extension.v1.CustomizeConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_examples_protos_custom_extension_example_custom_config_proto_init() }
func file_examples_protos_custom_extension_example_custom_config_proto_init() {
	if File_examples_protos_custom_extension_example_custom_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protos_custom_extension_example_custom_config_proto_rawDesc), len(file_examples_protos_custom_extension_example_custom_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_protos_custom_extension_example_custom_config_proto_goTypes,
		DependencyIndexes: file_examples_protos_custom_extension_example_custom_config_proto_depIdxs,
		MessageInfos:      file_examples_protos_custom_extension_example_custom_config_proto_msgTypes,
	}.Build()
	File_examples_protos_custom_extension_example_custom_config_proto = out.File
	file_examples_protos_custom_extension_example_custom_config_proto_goTypes = nil
	file_examples_protos_custom_extension_example_custom_config_proto_depIdxs = nil
}
