// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v5.28.3
// source: examples/protos/security/api/v1/greeter.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGreeterSayHelloAuthenticated = "/runtime.examples.security.api.v1.Greeter/SayHelloAuthenticated"
const OperationGreeterSayHelloAuthorized = "/runtime.examples.security.api.v1.Greeter/SayHelloAuthorized"
const OperationGreeterSayHelloPublic = "/runtime.examples.security.api.v1.Greeter/SayHelloPublic"

type GreeterHTTPServer interface {
	// SayHelloAuthenticated 2. Authenticated Access: Requires a valid identity (Authn).
	SayHelloAuthenticated(context.Context, *HelloRequest) (*HelloReply, error)
	// SayHelloAuthorized 3. Authorized Access: Requires a valid identity with specific roles (Authn + Authz).
	SayHelloAuthorized(context.Context, *HelloRequest) (*HelloReply, error)
	// SayHelloPublic 1. Public Access: No security checks required.
	// Using a leading dot to specify an absolute path for the option.
	SayHelloPublic(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/greeter/public/{name}", _Greeter_SayHelloPublic0_HTTP_Handler(srv))
	r.GET("/v1/greeter/authenticated/{name}", _Greeter_SayHelloAuthenticated0_HTTP_Handler(srv))
	r.GET("/v1/greeter/authorized/{name}", _Greeter_SayHelloAuthorized0_HTTP_Handler(srv))
}

func _Greeter_SayHelloPublic0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterSayHelloPublic)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHelloPublic(ctx, req.(*HelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_SayHelloAuthenticated0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterSayHelloAuthenticated)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHelloAuthenticated(ctx, req.(*HelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_SayHelloAuthorized0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterSayHelloAuthorized)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHelloAuthorized(ctx, req.(*HelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloReply)
		return ctx.Result(200, reply)
	}
}

type GreeterHTTPClient interface {
	// SayHelloAuthenticated 2. Authenticated Access: Requires a valid identity (Authn).
	SayHelloAuthenticated(ctx context.Context, req *HelloRequest, opts ...http.CallOption) (rsp *HelloReply, err error)
	// SayHelloAuthorized 3. Authorized Access: Requires a valid identity with specific roles (Authn + Authz).
	SayHelloAuthorized(ctx context.Context, req *HelloRequest, opts ...http.CallOption) (rsp *HelloReply, err error)
	// SayHelloPublic 1. Public Access: No security checks required.
	// Using a leading dot to specify an absolute path for the option.
	SayHelloPublic(ctx context.Context, req *HelloRequest, opts ...http.CallOption) (rsp *HelloReply, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(client *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

// SayHelloAuthenticated 2. Authenticated Access: Requires a valid identity (Authn).
func (c *GreeterHTTPClientImpl) SayHelloAuthenticated(ctx context.Context, in *HelloRequest, opts ...http.CallOption) (*HelloReply, error) {
	var out HelloReply
	pattern := "/v1/greeter/authenticated/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGreeterSayHelloAuthenticated))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SayHelloAuthorized 3. Authorized Access: Requires a valid identity with specific roles (Authn + Authz).
func (c *GreeterHTTPClientImpl) SayHelloAuthorized(ctx context.Context, in *HelloRequest, opts ...http.CallOption) (*HelloReply, error) {
	var out HelloReply
	pattern := "/v1/greeter/authorized/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGreeterSayHelloAuthorized))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SayHelloPublic 1. Public Access: No security checks required.
// Using a leading dot to specify an absolute path for the option.
func (c *GreeterHTTPClientImpl) SayHelloPublic(ctx context.Context, in *HelloRequest, opts ...http.CallOption) (*HelloReply, error) {
	var out HelloReply
	pattern := "/v1/greeter/public/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGreeterSayHelloPublic))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
