// Code generated by protoc-gen-go-security. DO NOT EDIT.
package v1

import security "github.com/origadmin/runtime/security"

func init() {
	serviceMap := map[string]string{
		"/runtime.examples.security.api.v1.Greeter/SayHelloPublic":        "public",
		"/runtime.examples.security.api.v1.Greeter/SayHelloAuthenticated": "authn-only",
		"/runtime.examples.security.api.v1.Greeter/SayHelloAuthorized":    "authn-authz",
	}
	gatewayMap := map[string]string{
		"GET:/v1/greeter/public/{name}":        "public",
		"GET:/v1/greeter/authenticated/{name}": "authn-only",
		"GET:/v1/greeter/authorized/{name}":    "authn-authz",
	}
	security.RegisterPolicies(serviceMap, gatewayMap)
}
