// Code generated by protoc-gen-go-security. DO NOT EDIT.

package v1

// PolicyMap is the mapping from method full name to security policy.
var PolicyMap = map[string]string{
	"/runtime.examples.security.api.v1.Greeter/SayHelloPublic":        "public",
	"/runtime.examples.security.api.v1.Greeter/SayHelloAuthenticated": "authn-only",
	"/runtime.examples.security.api.v1.Greeter/SayHelloAuthorized":    "authn-authz",
}
