// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: examples/protos/security/api/v1/greeter.proto

package v1

import (
	_ "github.com/origadmin/runtime/api/gen/go/security/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_examples_protos_security_api_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_security_api_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_examples_protos_security_api_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_examples_protos_security_api_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_security_api_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_examples_protos_security_api_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_examples_protos_security_api_v1_greeter_proto protoreflect.FileDescriptor

const file_examples_protos_security_api_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"-examples/protos/security/api/v1/greeter.proto\x12 runtime.examples.security.api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1asecurity/v1/security.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x88\x04\n" +
	"\aGreeter\x12\x9d\x01\n" +
	"\x0eSayHelloPublic\x12..runtime.examples.security.api.v1.HelloRequest\x1a,.runtime.examples.security.api.v1.HelloReply\"-\xea\xea\x1b\b\n" +
	"\x06public\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/greeter/public/{name}\x12\xaf\x01\n" +
	"\x15SayHelloAuthenticated\x12..runtime.examples.security.api.v1.HelloRequest\x1a,.runtime.examples.security.api.v1.HelloReply\"8\xea\xea\x1b\f\n" +
	"\n" +
	"authn-only\x82\xd3\xe4\x93\x02\"\x12 /v1/greeter/authenticated/{name}\x12\xaa\x01\n" +
	"\x12SayHelloAuthorized\x12..runtime.examples.security.api.v1.HelloRequest\x1a,.runtime.examples.security.api.v1.HelloReply\"6\xea\xea\x1b\r\n" +
	"\vauthn-authz\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/greeter/authorized/{name}B:Z8github.com/origadmin/runtime/examples/security/api/v1;v1b\x06proto3"

var (
	file_examples_protos_security_api_v1_greeter_proto_rawDescOnce sync.Once
	file_examples_protos_security_api_v1_greeter_proto_rawDescData []byte
)

func file_examples_protos_security_api_v1_greeter_proto_rawDescGZIP() []byte {
	file_examples_protos_security_api_v1_greeter_proto_rawDescOnce.Do(func() {
		file_examples_protos_security_api_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protos_security_api_v1_greeter_proto_rawDesc), len(file_examples_protos_security_api_v1_greeter_proto_rawDesc)))
	})
	return file_examples_protos_security_api_v1_greeter_proto_rawDescData
}

var file_examples_protos_security_api_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_protos_security_api_v1_greeter_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: runtime.examples.security.api.v1.HelloRequest
	(*HelloReply)(nil),   // 1: runtime.examples.security.api.v1.HelloReply
}
var file_examples_protos_security_api_v1_greeter_proto_depIdxs = []int32{
	0, // 0: runtime.examples.security.api.v1.Greeter.SayHelloPublic:input_type -> runtime.examples.security.api.v1.HelloRequest
	0, // 1: runtime.examples.security.api.v1.Greeter.SayHelloAuthenticated:input_type -> runtime.examples.security.api.v1.HelloRequest
	0, // 2: runtime.examples.security.api.v1.Greeter.SayHelloAuthorized:input_type -> runtime.examples.security.api.v1.HelloRequest
	1, // 3: runtime.examples.security.api.v1.Greeter.SayHelloPublic:output_type -> runtime.examples.security.api.v1.HelloReply
	1, // 4: runtime.examples.security.api.v1.Greeter.SayHelloAuthenticated:output_type -> runtime.examples.security.api.v1.HelloReply
	1, // 5: runtime.examples.security.api.v1.Greeter.SayHelloAuthorized:output_type -> runtime.examples.security.api.v1.HelloReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_protos_security_api_v1_greeter_proto_init() }
func file_examples_protos_security_api_v1_greeter_proto_init() {
	if File_examples_protos_security_api_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protos_security_api_v1_greeter_proto_rawDesc), len(file_examples_protos_security_api_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_protos_security_api_v1_greeter_proto_goTypes,
		DependencyIndexes: file_examples_protos_security_api_v1_greeter_proto_depIdxs,
		MessageInfos:      file_examples_protos_security_api_v1_greeter_proto_msgTypes,
	}.Build()
	File_examples_protos_security_api_v1_greeter_proto = out.File
	file_examples_protos_security_api_v1_greeter_proto_goTypes = nil
	file_examples_protos_security_api_v1_greeter_proto_depIdxs = nil
}
