// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: examples/protos/bootstrap_sample/bootstrap.proto

// Package name remains unchanged

package conf

import (
	v1 "github.com/origadmin/runtime/api/gen/go/config/app/v1"
	v16 "github.com/origadmin/runtime/api/gen/go/config/broker/v1"
	v12 "github.com/origadmin/runtime/api/gen/go/config/data/v1"
	v15 "github.com/origadmin/runtime/api/gen/go/config/discovery/v1"
	v13 "github.com/origadmin/runtime/api/gen/go/config/logger/v1"
	v17 "github.com/origadmin/runtime/api/gen/go/config/middleware/v1"
	v18 "github.com/origadmin/runtime/api/gen/go/config/security/v1"
	v14 "github.com/origadmin/runtime/api/gen/go/config/trace/v1"
	v11 "github.com/origadmin/runtime/api/gen/go/config/transport/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap is the root configuration example for the entire application.
// The new structure aggregates all configuration items into logical groups, making it clearer and easier to understand.
type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// App contains application-level metadata (e.g., name, version, environment).
	App *v1.App `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// Servers holds configurations for all network servers (HTTP, gRPC, WebSocket).
	// This now uses the Servers collection from the transport module.
	Servers *v11.Servers `protobuf:"bytes,2,opt,name=servers,proto3" json:"servers,omitempty"`
	// Data holds configurations for all data sources (databases, caches).
	Data *v12.Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Logger configures the application's logging behavior.
	Logger *v13.Logger `protobuf:"bytes,4,opt,name=logger,proto3" json:"logger,omitempty"`
	// Trace configures the distributed tracing system.
	Trace *v14.Trace `protobuf:"bytes,5,opt,name=trace,proto3" json:"trace,omitempty"`
	// Discovery configures the service discovery client.
	Discoveries *v15.Discoveries `protobuf:"bytes,6,opt,name=discoveries,proto3" json:"discoveries,omitempty"`
	// Broker configures the message brokers.
	Brokers *v16.Brokers `protobuf:"bytes,7,opt,name=brokers,proto3" json:"brokers,omitempty"`
	// Middlewares defines the middleware chain.
	Middlewares *v17.Middlewares `protobuf:"bytes,8,opt,name=middlewares,proto3" json:"middlewares,omitempty"`
	// Security defines authentication and authorization policies.
	Security *v18.Security `protobuf:"bytes,9,opt,name=security,proto3" json:"security,omitempty"`
	// Clients holds configurations for all network clients (HTTP, gRPC).
	// This now uses the Clients collection from the transport module.
	Clients       *v11.Clients `protobuf:"bytes,10,opt,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_examples_protos_bootstrap_sample_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_bootstrap_sample_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetApp() *v1.App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *Bootstrap) GetServers() *v11.Servers {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Bootstrap) GetData() *v12.Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetLogger() *v13.Logger {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *Bootstrap) GetTrace() *v14.Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Bootstrap) GetDiscoveries() *v15.Discoveries {
	if x != nil {
		return x.Discoveries
	}
	return nil
}

func (x *Bootstrap) GetBrokers() *v16.Brokers {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *Bootstrap) GetMiddlewares() *v17.Middlewares {
	if x != nil {
		return x.Middlewares
	}
	return nil
}

func (x *Bootstrap) GetSecurity() *v18.Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *Bootstrap) GetClients() *v11.Clients {
	if x != nil {
		return x.Clients
	}
	return nil
}

var File_examples_protos_bootstrap_sample_bootstrap_proto protoreflect.FileDescriptor

const file_examples_protos_bootstrap_sample_bootstrap_proto_rawDesc = "" +
	"\n" +
	"0examples/protos/bootstrap_sample/bootstrap.proto\x12\x10bootstrap_sample\x1a\x17config/app/v1/app.proto\x1a\x1dconfig/broker/v1/broker.proto\x1a\x19config/data/v1/data.proto\x1a#config/discovery/v1/discovery.proto\x1a\x1dconfig/logger/v1/logger.proto\x1a%config/middleware/v1/middleware.proto\x1a!config/security/v1/security.proto\x1a\x1bconfig/trace/v1/trace.proto\x1a#config/transport/v1/transport.proto\"\xa3\x04\n" +
	"\tBootstrap\x12$\n" +
	"\x03app\x18\x01 \x01(\v2\x12.config.app.v1.AppR\x03app\x126\n" +
	"\aservers\x18\x02 \x01(\v2\x1c.config.transport.v1.ServersR\aservers\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.config.data.v1.DataR\x04data\x120\n" +
	"\x06logger\x18\x04 \x01(\v2\x18.config.logger.v1.LoggerR\x06logger\x12,\n" +
	"\x05trace\x18\x05 \x01(\v2\x16.config.trace.v1.TraceR\x05trace\x12B\n" +
	"\vdiscoveries\x18\x06 \x01(\v2 .config.discovery.v1.DiscoveriesR\vdiscoveries\x123\n" +
	"\abrokers\x18\a \x01(\v2\x19.config.broker.v1.BrokersR\abrokers\x12C\n" +
	"\vmiddlewares\x18\b \x01(\v2!.config.middleware.v1.MiddlewaresR\vmiddlewares\x128\n" +
	"\bsecurity\x18\t \x01(\v2\x1c.config.security.v1.SecurityR\bsecurity\x126\n" +
	"\aclients\x18\n" +
	" \x01(\v2\x1c.config.transport.v1.ClientsR\aclientsBEZCgithub.com/origadmin/runtime/examples/configs/bootstrap_sample;confb\x06proto3"

var (
	file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescOnce sync.Once
	file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescData []byte
)

func file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescGZIP() []byte {
	file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescOnce.Do(func() {
		file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protos_bootstrap_sample_bootstrap_proto_rawDesc), len(file_examples_protos_bootstrap_sample_bootstrap_proto_rawDesc)))
	})
	return file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescData
}

var file_examples_protos_bootstrap_sample_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_protos_bootstrap_sample_bootstrap_proto_goTypes = []any{
	(*Bootstrap)(nil),       // 0: bootstrap_sample.Bootstrap
	(*v1.App)(nil),          // 1: config.app.v1.App
	(*v11.Servers)(nil),     // 2: config.transport.v1.Servers
	(*v12.Data)(nil),        // 3: config.data.v1.Data
	(*v13.Logger)(nil),      // 4: config.logger.v1.Logger
	(*v14.Trace)(nil),       // 5: config.trace.v1.Trace
	(*v15.Discoveries)(nil), // 6: config.discovery.v1.Discoveries
	(*v16.Brokers)(nil),     // 7: config.broker.v1.Brokers
	(*v17.Middlewares)(nil), // 8: config.middleware.v1.Middlewares
	(*v18.Security)(nil),    // 9: config.security.v1.Security
	(*v11.Clients)(nil),     // 10: config.transport.v1.Clients
}
var file_examples_protos_bootstrap_sample_bootstrap_proto_depIdxs = []int32{
	1,  // 0: bootstrap_sample.Bootstrap.app:type_name -> config.app.v1.App
	2,  // 1: bootstrap_sample.Bootstrap.servers:type_name -> config.transport.v1.Servers
	3,  // 2: bootstrap_sample.Bootstrap.data:type_name -> config.data.v1.Data
	4,  // 3: bootstrap_sample.Bootstrap.logger:type_name -> config.logger.v1.Logger
	5,  // 4: bootstrap_sample.Bootstrap.trace:type_name -> config.trace.v1.Trace
	6,  // 5: bootstrap_sample.Bootstrap.discoveries:type_name -> config.discovery.v1.Discoveries
	7,  // 6: bootstrap_sample.Bootstrap.brokers:type_name -> config.broker.v1.Brokers
	8,  // 7: bootstrap_sample.Bootstrap.middlewares:type_name -> config.middleware.v1.Middlewares
	9,  // 8: bootstrap_sample.Bootstrap.security:type_name -> config.security.v1.Security
	10, // 9: bootstrap_sample.Bootstrap.clients:type_name -> config.transport.v1.Clients
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_examples_protos_bootstrap_sample_bootstrap_proto_init() }
func file_examples_protos_bootstrap_sample_bootstrap_proto_init() {
	if File_examples_protos_bootstrap_sample_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protos_bootstrap_sample_bootstrap_proto_rawDesc), len(file_examples_protos_bootstrap_sample_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_protos_bootstrap_sample_bootstrap_proto_goTypes,
		DependencyIndexes: file_examples_protos_bootstrap_sample_bootstrap_proto_depIdxs,
		MessageInfos:      file_examples_protos_bootstrap_sample_bootstrap_proto_msgTypes,
	}.Build()
	File_examples_protos_bootstrap_sample_bootstrap_proto = out.File
	file_examples_protos_bootstrap_sample_bootstrap_proto_goTypes = nil
	file_examples_protos_bootstrap_sample_bootstrap_proto_depIdxs = nil
}
