// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: examples/protos/bootstrap_sample/bootstrap.proto

package conf

import (
	v1 "github.com/origadmin/runtime/api/gen/go/runtime/logger/v1"
	v11 "github.com/origadmin/runtime/api/gen/go/runtime/transport/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap 是一个最小化的应用顶层配置结构，聚合了核心组件的配置
type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logger        *v1.Logger             `protobuf:"bytes,1,opt,name=logger,proto3" json:"logger,omitempty"`
	Servers       *v11.Servers           `protobuf:"bytes,2,opt,name=servers,proto3" json:"servers,omitempty"` // 其他组件配置可根据需要在此处添加
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_examples_protos_bootstrap_sample_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_bootstrap_sample_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetLogger() *v1.Logger {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *Bootstrap) GetServers() *v11.Servers {
	if x != nil {
		return x.Servers
	}
	return nil
}

var File_examples_protos_bootstrap_sample_bootstrap_proto protoreflect.FileDescriptor

const file_examples_protos_bootstrap_sample_bootstrap_proto_rawDesc = "" +
	"\n" +
	"0examples/protos/bootstrap_sample/bootstrap.proto\x12\x10bootstrap_sample\x1a\x1eruntime/logger/v1/logger.proto\x1a$runtime/transport/v1/transport.proto\"w\n" +
	"\tBootstrap\x121\n" +
	"\x06logger\x18\x01 \x01(\v2\x19.runtime.logger.v1.LoggerR\x06logger\x127\n" +
	"\aservers\x18\x02 \x01(\v2\x1d.runtime.transport.v1.ServersR\aserversBEZCgithub.com/origadmin/runtime/examples/configs/bootstrap_sample;confb\x06proto3"

var (
	file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescOnce sync.Once
	file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescData []byte
)

func file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescGZIP() []byte {
	file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescOnce.Do(func() {
		file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protos_bootstrap_sample_bootstrap_proto_rawDesc), len(file_examples_protos_bootstrap_sample_bootstrap_proto_rawDesc)))
	})
	return file_examples_protos_bootstrap_sample_bootstrap_proto_rawDescData
}

var file_examples_protos_bootstrap_sample_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_protos_bootstrap_sample_bootstrap_proto_goTypes = []any{
	(*Bootstrap)(nil),   // 0: bootstrap_sample.Bootstrap
	(*v1.Logger)(nil),   // 1: runtime.logger.v1.Logger
	(*v11.Servers)(nil), // 2: runtime.transport.v1.Servers
}
var file_examples_protos_bootstrap_sample_bootstrap_proto_depIdxs = []int32{
	1, // 0: bootstrap_sample.Bootstrap.logger:type_name -> runtime.logger.v1.Logger
	2, // 1: bootstrap_sample.Bootstrap.servers:type_name -> runtime.transport.v1.Servers
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_examples_protos_bootstrap_sample_bootstrap_proto_init() }
func file_examples_protos_bootstrap_sample_bootstrap_proto_init() {
	if File_examples_protos_bootstrap_sample_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protos_bootstrap_sample_bootstrap_proto_rawDesc), len(file_examples_protos_bootstrap_sample_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_protos_bootstrap_sample_bootstrap_proto_goTypes,
		DependencyIndexes: file_examples_protos_bootstrap_sample_bootstrap_proto_depIdxs,
		MessageInfos:      file_examples_protos_bootstrap_sample_bootstrap_proto_msgTypes,
	}.Build()
	File_examples_protos_bootstrap_sample_bootstrap_proto = out.File
	file_examples_protos_bootstrap_sample_bootstrap_proto_goTypes = nil
	file_examples_protos_bootstrap_sample_bootstrap_proto_depIdxs = nil
}
