// Configuration for a microservice with HTTP server and gRPC client
// This file defines the configuration for a microservice that provides an HTTP server interface and calls gRPC services

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: examples/protos/http_server_grpc_client/bootstrap.proto

// Package name to prevent naming conflicts

package conf

import (
	v11 "github.com/origadmin/runtime/api/gen/go/config/discovery/v1"
	v1 "github.com/origadmin/runtime/api/gen/go/config/transport/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap is the top-level configuration for a microservice with HTTP server and gRPC client
// This architecture pattern is suitable for scenarios that need to provide RESTful APIs while calling other gRPC services
type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server configuration list
	// Typically, this would configure an HTTP server to provide APIs
	// For example:
	// - Port number
	// - Middleware configuration
	// - Timeout settings
	Servers []*v1.Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	// Downstream gRPC client configuration mapping
	// The key is the logical name of the client, used to reference specific clients in code
	// For example:
	// - "user-service-client"
	// - "order-service-client"
	Clients       map[string]*ClientConfig `protobuf:"bytes,2,rep,name=clients,proto3" json:"clients,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_examples_protos_http_server_grpc_client_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_http_server_grpc_client_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServers() []*v1.Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Bootstrap) GetClients() map[string]*ClientConfig {
	if x != nil {
		return x.Clients
	}
	return nil
}

// ClientConfig combines all configurations needed for a gRPC client
// It includes service discovery and transport layer configurations
type ClientConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Business-level client configuration
	// Mainly configures how to discover and select gRPC service instances, for example:
	// - Service discovery method (direct, DNS, Consul, etc.)
	// - Load balancing strategy
	// - Circuit breaking and fallback configuration
	Endpoint *v11.Endpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Transport-level client configuration
	// Mainly configures how to communicate with gRPC service instances, for example:
	// - Connection pool configuration
	// - Timeout settings
	// - Retry policy
	// - TLS configuration
	Transport     *v1.Client `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_examples_protos_http_server_grpc_client_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_http_server_grpc_client_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *ClientConfig) GetEndpoint() *v11.Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *ClientConfig) GetTransport() *v1.Client {
	if x != nil {
		return x.Transport
	}
	return nil
}

var File_examples_protos_http_server_grpc_client_bootstrap_proto protoreflect.FileDescriptor

const file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDesc = "" +
	"\n" +
	"7examples/protos/http_server_grpc_client/bootstrap.proto\x12 examples.http_server_grpc_client\x1a#config/transport/v1/transport.proto\x1a\"config/discovery/v1/endpoint.proto\"\x82\x02\n" +
	"\tBootstrap\x125\n" +
	"\aservers\x18\x01 \x03(\v2\x1b.config.transport.v1.ServerR\aservers\x12R\n" +
	"\aclients\x18\x02 \x03(\v28.examples.http_server_grpc_client.Bootstrap.ClientsEntryR\aclients\x1aj\n" +
	"\fClientsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12D\n" +
	"\x05value\x18\x02 \x01(\v2..examples.http_server_grpc_client.ClientConfigR\x05value:\x028\x01\"\x84\x01\n" +
	"\fClientConfig\x129\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1d.config.discovery.v1.EndpointR\bendpoint\x129\n" +
	"\ttransport\x18\x02 \x01(\v2\x1b.config.transport.v1.ClientR\ttransportB%Z#./http_server_grpc_client/conf;confb\x06proto3"

var (
	file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDescOnce sync.Once
	file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDescData []byte
)

func file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDescGZIP() []byte {
	file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDescOnce.Do(func() {
		file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDesc), len(file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDesc)))
	})
	return file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDescData
}

var file_examples_protos_http_server_grpc_client_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_examples_protos_http_server_grpc_client_bootstrap_proto_goTypes = []any{
	(*Bootstrap)(nil),    // 0: examples.http_server_grpc_client.Bootstrap
	(*ClientConfig)(nil), // 1: examples.http_server_grpc_client.ClientConfig
	nil,                  // 2: examples.http_server_grpc_client.Bootstrap.ClientsEntry
	(*v1.Server)(nil),    // 3: config.transport.v1.Server
	(*v11.Endpoint)(nil), // 4: config.discovery.v1.Endpoint
	(*v1.Client)(nil),    // 5: config.transport.v1.Client
}
var file_examples_protos_http_server_grpc_client_bootstrap_proto_depIdxs = []int32{
	3, // 0: examples.http_server_grpc_client.Bootstrap.servers:type_name -> config.transport.v1.Server
	2, // 1: examples.http_server_grpc_client.Bootstrap.clients:type_name -> examples.http_server_grpc_client.Bootstrap.ClientsEntry
	4, // 2: examples.http_server_grpc_client.ClientConfig.endpoint:type_name -> config.discovery.v1.Endpoint
	5, // 3: examples.http_server_grpc_client.ClientConfig.transport:type_name -> config.transport.v1.Client
	1, // 4: examples.http_server_grpc_client.Bootstrap.ClientsEntry.value:type_name -> examples.http_server_grpc_client.ClientConfig
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_examples_protos_http_server_grpc_client_bootstrap_proto_init() }
func file_examples_protos_http_server_grpc_client_bootstrap_proto_init() {
	if File_examples_protos_http_server_grpc_client_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDesc), len(file_examples_protos_http_server_grpc_client_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_protos_http_server_grpc_client_bootstrap_proto_goTypes,
		DependencyIndexes: file_examples_protos_http_server_grpc_client_bootstrap_proto_depIdxs,
		MessageInfos:      file_examples_protos_http_server_grpc_client_bootstrap_proto_msgTypes,
	}.Build()
	File_examples_protos_http_server_grpc_client_bootstrap_proto = out.File
	file_examples_protos_http_server_grpc_client_bootstrap_proto_goTypes = nil
	file_examples_protos_http_server_grpc_client_bootstrap_proto_depIdxs = nil
}
