// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: examples/protos/custom_extension/any_example.proto

package conf

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MiddlewareAny with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MiddlewareAny) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MiddlewareAny with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MiddlewareAnyMultiError, or
// nil if none found.
func (m *MiddlewareAny) ValidateAll() error {
	return m.validate(true)
}

func (m *MiddlewareAny) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Type

	if m.Customize != nil {

		if all {
			switch v := interface{}(m.GetCustomize()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MiddlewareAnyValidationError{
						field:  "Customize",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MiddlewareAnyValidationError{
						field:  "Customize",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCustomize()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MiddlewareAnyValidationError{
					field:  "Customize",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MiddlewareAnyMultiError(errors)
	}

	return nil
}

// MiddlewareAnyMultiError is an error wrapping multiple validation errors
// returned by MiddlewareAny.ValidateAll() if the designated constraints
// aren't met.
type MiddlewareAnyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MiddlewareAnyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MiddlewareAnyMultiError) AllErrors() []error { return m }

// MiddlewareAnyValidationError is the validation error returned by
// MiddlewareAny.Validate if the designated constraints aren't met.
type MiddlewareAnyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MiddlewareAnyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MiddlewareAnyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MiddlewareAnyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MiddlewareAnyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MiddlewareAnyValidationError) ErrorName() string { return "MiddlewareAnyValidationError" }

// Error satisfies the builtin error interface
func (e MiddlewareAnyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMiddlewareAny.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MiddlewareAnyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MiddlewareAnyValidationError{}
