// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: examples/protos/custom_extension/any_example.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Middleware message using google.protobuf.Any.
// This approach is more complex when loading from a config file without a '@type' field.
type MiddlewareAny struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// The 'customize' field expects a packed message with a type URL.
	// Loading a plain YAML/JSON object into this directly will fail.
	Customize     *anypb.Any `protobuf:"bytes,100,opt,name=customize,proto3,oneof" json:"customize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlewareAny) Reset() {
	*x = MiddlewareAny{}
	mi := &file_examples_protos_custom_extension_any_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareAny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareAny) ProtoMessage() {}

func (x *MiddlewareAny) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_custom_extension_any_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareAny.ProtoReflect.Descriptor instead.
func (*MiddlewareAny) Descriptor() ([]byte, []int) {
	return file_examples_protos_custom_extension_any_example_proto_rawDescGZIP(), []int{0}
}

func (x *MiddlewareAny) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MiddlewareAny) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MiddlewareAny) GetCustomize() *anypb.Any {
	if x != nil {
		return x.Customize
	}
	return nil
}

var File_examples_protos_custom_extension_any_example_proto protoreflect.FileDescriptor

const file_examples_protos_custom_extension_any_example_proto_rawDesc = "" +
	"\n" +
	"2examples/protos/custom_extension/any_example.proto\x12\x19examples.custom_extension\x1a\x19google/protobuf/any.proto\"~\n" +
	"\rMiddlewareAny\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x127\n" +
	"\tcustomize\x18d \x01(\v2\x14.google.protobuf.AnyH\x00R\tcustomize\x88\x01\x01B\f\n" +
	"\n" +
	"_customizeB\x1eZ\x1c./custom_extension/conf;confb\x06proto3"

var (
	file_examples_protos_custom_extension_any_example_proto_rawDescOnce sync.Once
	file_examples_protos_custom_extension_any_example_proto_rawDescData []byte
)

func file_examples_protos_custom_extension_any_example_proto_rawDescGZIP() []byte {
	file_examples_protos_custom_extension_any_example_proto_rawDescOnce.Do(func() {
		file_examples_protos_custom_extension_any_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protos_custom_extension_any_example_proto_rawDesc), len(file_examples_protos_custom_extension_any_example_proto_rawDesc)))
	})
	return file_examples_protos_custom_extension_any_example_proto_rawDescData
}

var file_examples_protos_custom_extension_any_example_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_protos_custom_extension_any_example_proto_goTypes = []any{
	(*MiddlewareAny)(nil), // 0: examples.custom_extension.MiddlewareAny
	(*anypb.Any)(nil),     // 1: google.protobuf.Any
}
var file_examples_protos_custom_extension_any_example_proto_depIdxs = []int32{
	1, // 0: examples.custom_extension.MiddlewareAny.customize:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_examples_protos_custom_extension_any_example_proto_init() }
func file_examples_protos_custom_extension_any_example_proto_init() {
	if File_examples_protos_custom_extension_any_example_proto != nil {
		return
	}
	file_examples_protos_custom_extension_any_example_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protos_custom_extension_any_example_proto_rawDesc), len(file_examples_protos_custom_extension_any_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_protos_custom_extension_any_example_proto_goTypes,
		DependencyIndexes: file_examples_protos_custom_extension_any_example_proto_depIdxs,
		MessageInfos:      file_examples_protos_custom_extension_any_example_proto_msgTypes,
	}.Build()
	File_examples_protos_custom_extension_any_example_proto = out.File
	file_examples_protos_custom_extension_any_example_proto_goTypes = nil
	file_examples_protos_custom_extension_any_example_proto_depIdxs = nil
}
