// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: examples/protos/custom_extension/custom_config.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CustomAuthConfig is the strongly-typed representation of our custom middleware config.
// We will convert the generic Struct into this specific type in our Go code.
type CustomAuthConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The policy definition, e.g., using Casbin model.
	Policy string `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	// The required scope for the endpoint.
	RequiredScope string `protobuf:"bytes,2,opt,name=required_scope,json=requiredScope,proto3" json:"required_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomAuthConfig) Reset() {
	*x = CustomAuthConfig{}
	mi := &file_examples_protos_custom_extension_custom_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomAuthConfig) ProtoMessage() {}

func (x *CustomAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_custom_extension_custom_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomAuthConfig.ProtoReflect.Descriptor instead.
func (*CustomAuthConfig) Descriptor() ([]byte, []int) {
	return file_examples_protos_custom_extension_custom_config_proto_rawDescGZIP(), []int{0}
}

func (x *CustomAuthConfig) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *CustomAuthConfig) GetRequiredScope() string {
	if x != nil {
		return x.RequiredScope
	}
	return ""
}

// Custom configuration message
type CustomConfig struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	CustomField   string                     `protobuf:"bytes,1,opt,name=custom_field,json=customField,proto3" json:"custom_field,omitempty"`
	CustomNumber  int32                      `protobuf:"varint,2,opt,name=custom_number,json=customNumber,proto3" json:"custom_number,omitempty"`
	Items         []string                   `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Nested        *CustomConfig_NestedConfig `protobuf:"bytes,4,opt,name=nested,proto3" json:"nested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomConfig) Reset() {
	*x = CustomConfig{}
	mi := &file_examples_protos_custom_extension_custom_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomConfig) ProtoMessage() {}

func (x *CustomConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_custom_extension_custom_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomConfig.ProtoReflect.Descriptor instead.
func (*CustomConfig) Descriptor() ([]byte, []int) {
	return file_examples_protos_custom_extension_custom_config_proto_rawDescGZIP(), []int{1}
}

func (x *CustomConfig) GetCustomField() string {
	if x != nil {
		return x.CustomField
	}
	return ""
}

func (x *CustomConfig) GetCustomNumber() int32 {
	if x != nil {
		return x.CustomNumber
	}
	return 0
}

func (x *CustomConfig) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CustomConfig) GetNested() *CustomConfig_NestedConfig {
	if x != nil {
		return x.Nested
	}
	return nil
}

// Application configuration
type ApplicationConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CustomizeConfig *structpb.Struct       `protobuf:"bytes,3,opt,name=customize_config,proto3,oneof" json:"customize_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplicationConfig) Reset() {
	*x = ApplicationConfig{}
	mi := &file_examples_protos_custom_extension_custom_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfig) ProtoMessage() {}

func (x *ApplicationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_custom_extension_custom_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfig.ProtoReflect.Descriptor instead.
func (*ApplicationConfig) Descriptor() ([]byte, []int) {
	return file_examples_protos_custom_extension_custom_config_proto_rawDescGZIP(), []int{2}
}

func (x *ApplicationConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ApplicationConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationConfig) GetCustomizeConfig() *structpb.Struct {
	if x != nil {
		return x.CustomizeConfig
	}
	return nil
}

type CustomConfig_NestedConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomConfig_NestedConfig) Reset() {
	*x = CustomConfig_NestedConfig{}
	mi := &file_examples_protos_custom_extension_custom_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomConfig_NestedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomConfig_NestedConfig) ProtoMessage() {}

func (x *CustomConfig_NestedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_custom_extension_custom_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomConfig_NestedConfig.ProtoReflect.Descriptor instead.
func (*CustomConfig_NestedConfig) Descriptor() ([]byte, []int) {
	return file_examples_protos_custom_extension_custom_config_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CustomConfig_NestedConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CustomConfig_NestedConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_examples_protos_custom_extension_custom_config_proto protoreflect.FileDescriptor

const file_examples_protos_custom_extension_custom_config_proto_rawDesc = "" +
	"\n" +
	"4examples/protos/custom_extension/custom_config.proto\x12!runtime.examples.custom_extension\x1a\x1cgoogle/protobuf/struct.proto\"Q\n" +
	"\x10CustomAuthConfig\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\tR\x06policy\x12%\n" +
	"\x0erequired_scope\x18\x02 \x01(\tR\rrequiredScope\"\x80\x02\n" +
	"\fCustomConfig\x12!\n" +
	"\fcustom_field\x18\x01 \x01(\tR\vcustomField\x12#\n" +
	"\rcustom_number\x18\x02 \x01(\x05R\fcustomNumber\x12\x14\n" +
	"\x05items\x18\x03 \x03(\tR\x05items\x12T\n" +
	"\x06nested\x18\x04 \x01(\v2<.runtime.examples.custom_extension.CustomConfig.NestedConfigR\x06nested\x1a<\n" +
	"\fNestedConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa0\x01\n" +
	"\x11ApplicationConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12H\n" +
	"\x10customize_config\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x00R\x10customize_config\x88\x01\x01B\x13\n" +
	"\x11_customize_configB\x1eZ\x1c./custom_extension/conf;confb\x06proto3"

var (
	file_examples_protos_custom_extension_custom_config_proto_rawDescOnce sync.Once
	file_examples_protos_custom_extension_custom_config_proto_rawDescData []byte
)

func file_examples_protos_custom_extension_custom_config_proto_rawDescGZIP() []byte {
	file_examples_protos_custom_extension_custom_config_proto_rawDescOnce.Do(func() {
		file_examples_protos_custom_extension_custom_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protos_custom_extension_custom_config_proto_rawDesc), len(file_examples_protos_custom_extension_custom_config_proto_rawDesc)))
	})
	return file_examples_protos_custom_extension_custom_config_proto_rawDescData
}

var file_examples_protos_custom_extension_custom_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_examples_protos_custom_extension_custom_config_proto_goTypes = []any{
	(*CustomAuthConfig)(nil),          // 0: runtime.examples.custom_extension.CustomAuthConfig
	(*CustomConfig)(nil),              // 1: runtime.examples.custom_extension.CustomConfig
	(*ApplicationConfig)(nil),         // 2: runtime.examples.custom_extension.ApplicationConfig
	(*CustomConfig_NestedConfig)(nil), // 3: runtime.examples.custom_extension.CustomConfig.NestedConfig
	(*structpb.Struct)(nil),           // 4: google.protobuf.Struct
}
var file_examples_protos_custom_extension_custom_config_proto_depIdxs = []int32{
	3, // 0: runtime.examples.custom_extension.CustomConfig.nested:type_name -> runtime.examples.custom_extension.CustomConfig.NestedConfig
	4, // 1: runtime.examples.custom_extension.ApplicationConfig.customize_config:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_examples_protos_custom_extension_custom_config_proto_init() }
func file_examples_protos_custom_extension_custom_config_proto_init() {
	if File_examples_protos_custom_extension_custom_config_proto != nil {
		return
	}
	file_examples_protos_custom_extension_custom_config_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protos_custom_extension_custom_config_proto_rawDesc), len(file_examples_protos_custom_extension_custom_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_protos_custom_extension_custom_config_proto_goTypes,
		DependencyIndexes: file_examples_protos_custom_extension_custom_config_proto_depIdxs,
		MessageInfos:      file_examples_protos_custom_extension_custom_config_proto_msgTypes,
	}.Build()
	File_examples_protos_custom_extension_custom_config_proto = out.File
	file_examples_protos_custom_extension_custom_config_proto_goTypes = nil
	file_examples_protos_custom_extension_custom_config_proto_depIdxs = nil
}
