// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: examples/protos/custom_extension/struct_example.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Middleware message using google.protobuf.Struct for flexible custom configuration.
// This is the recommended approach.
type MiddlewareStruct struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// The 'customize' field can hold any JSON-like structure from the config file,
	// which will be automatically parsed into a Struct.
	Customize     *structpb.Struct `protobuf:"bytes,100,opt,name=customize,proto3,oneof" json:"customize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlewareStruct) Reset() {
	*x = MiddlewareStruct{}
	mi := &file_examples_protos_custom_extension_struct_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareStruct) ProtoMessage() {}

func (x *MiddlewareStruct) ProtoReflect() protoreflect.Message {
	mi := &file_examples_protos_custom_extension_struct_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareStruct.ProtoReflect.Descriptor instead.
func (*MiddlewareStruct) Descriptor() ([]byte, []int) {
	return file_examples_protos_custom_extension_struct_example_proto_rawDescGZIP(), []int{0}
}

func (x *MiddlewareStruct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MiddlewareStruct) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MiddlewareStruct) GetCustomize() *structpb.Struct {
	if x != nil {
		return x.Customize
	}
	return nil
}

var File_examples_protos_custom_extension_struct_example_proto protoreflect.FileDescriptor

const file_examples_protos_custom_extension_struct_example_proto_rawDesc = "" +
	"\n" +
	"5examples/protos/custom_extension/struct_example.proto\x12!runtime.examples.custom_extension\x1a\x1cgoogle/protobuf/struct.proto\"\x84\x01\n" +
	"\x10MiddlewareStruct\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12:\n" +
	"\tcustomize\x18d \x01(\v2\x17.google.protobuf.StructH\x00R\tcustomize\x88\x01\x01B\f\n" +
	"\n" +
	"_customizeB\x1eZ\x1c./custom_extension/conf;confb\x06proto3"

var (
	file_examples_protos_custom_extension_struct_example_proto_rawDescOnce sync.Once
	file_examples_protos_custom_extension_struct_example_proto_rawDescData []byte
)

func file_examples_protos_custom_extension_struct_example_proto_rawDescGZIP() []byte {
	file_examples_protos_custom_extension_struct_example_proto_rawDescOnce.Do(func() {
		file_examples_protos_custom_extension_struct_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_protos_custom_extension_struct_example_proto_rawDesc), len(file_examples_protos_custom_extension_struct_example_proto_rawDesc)))
	})
	return file_examples_protos_custom_extension_struct_example_proto_rawDescData
}

var file_examples_protos_custom_extension_struct_example_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_protos_custom_extension_struct_example_proto_goTypes = []any{
	(*MiddlewareStruct)(nil), // 0: runtime.examples.custom_extension.MiddlewareStruct
	(*structpb.Struct)(nil),  // 1: google.protobuf.Struct
}
var file_examples_protos_custom_extension_struct_example_proto_depIdxs = []int32{
	1, // 0: runtime.examples.custom_extension.MiddlewareStruct.customize:type_name -> google.protobuf.Struct
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_examples_protos_custom_extension_struct_example_proto_init() }
func file_examples_protos_custom_extension_struct_example_proto_init() {
	if File_examples_protos_custom_extension_struct_example_proto != nil {
		return
	}
	file_examples_protos_custom_extension_struct_example_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_protos_custom_extension_struct_example_proto_rawDesc), len(file_examples_protos_custom_extension_struct_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_protos_custom_extension_struct_example_proto_goTypes,
		DependencyIndexes: file_examples_protos_custom_extension_struct_example_proto_depIdxs,
		MessageInfos:      file_examples_protos_custom_extension_struct_example_proto_msgTypes,
	}.Build()
	File_examples_protos_custom_extension_struct_example_proto = out.File
	file_examples_protos_custom_extension_struct_example_proto_goTypes = nil
	file_examples_protos_custom_extension_struct_example_proto_depIdxs = nil
}
