// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: examples/protos/custom_extension/struct_example.proto

package conf

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MiddlewareStruct with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *MiddlewareStruct) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MiddlewareStruct with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MiddlewareStructMultiError, or nil if none found.
func (m *MiddlewareStruct) ValidateAll() error {
	return m.validate(true)
}

func (m *MiddlewareStruct) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Type

	if m.Customize != nil {

		if all {
			switch v := interface{}(m.GetCustomize()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MiddlewareStructValidationError{
						field:  "Customize",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MiddlewareStructValidationError{
						field:  "Customize",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCustomize()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MiddlewareStructValidationError{
					field:  "Customize",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MiddlewareStructMultiError(errors)
	}

	return nil
}

// MiddlewareStructMultiError is an error wrapping multiple validation errors
// returned by MiddlewareStruct.ValidateAll() if the designated constraints
// aren't met.
type MiddlewareStructMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MiddlewareStructMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MiddlewareStructMultiError) AllErrors() []error { return m }

// MiddlewareStructValidationError is the validation error returned by
// MiddlewareStruct.Validate if the designated constraints aren't met.
type MiddlewareStructValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MiddlewareStructValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MiddlewareStructValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MiddlewareStructValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MiddlewareStructValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MiddlewareStructValidationError) ErrorName() string { return "MiddlewareStructValidationError" }

// Error satisfies the builtin error interface
func (e MiddlewareStructValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMiddlewareStruct.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MiddlewareStructValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MiddlewareStructValidationError{}
